INSERT INTO [dbo].[Details] ([userid], [tweet]) VALUES 
('	pbelmore	','	So Nightcrawler is going to be good right? Ill be pretty bummed if it isnt.	'),
('	Nfischer96	','	I want to watch Nightcrawler	'),
('	John_Nissan	','	robpizzola keep seeing reviews for Birdman. Positive ones. Like really good	'),
('	matt5501	','	I cant wait to see nightcrawler	'),
('	SlateArnold	','	Nightcrawler looks like itll be good	'),
('	BrentPrimus	','	BIRDMAN: About as good as a movie can possibly be. Grade: A+.	'),
('	ariicab	','	GuadaRubin annabelle?	'),
('	RDotG	','	I wanna see Nightcrawler.	'),
('	cyrusgel35	','	Anyone know what that Nightcrawler movie is about?	'),
('	imErikB	','	Gotta see Nightcrawler	'),
('	cholinko	','	No longer on the run...#Beyonce and #JayZ dropping by for the NYC premiere of #Nightcrawler with… http://t.co/7UevS0qzWm	'),
('	Daily_Bruise	','	"Nightcrawler" looks AWESOME!!	'),
('	JUSTIN_time32	','	Gyllenhall looks like a damn rapist in Nightcrawler	'),
('	daniabieber2013	','	karmabieber01  have you seen Annabelle?	'),
('	ShaneOMac717	','	Need someone to see Nightcrawler with this weekend!	'),
('	CAGRustyRyan	','	This Nightcrawler film might get me to the movies.	'),
('	Halezzzzzzzzzzz	','	brookeG105 is the best movie buddy ever! #TheBestOfMe	'),
('	Shartmeier69	','	Someone see Nightcrawler with meh Friday.	'),
('	WARDrozay	','	nightcrawler looks unbelievable	'),
('	ThatRavensFan	','	I want to see #Nightcrawler...	'),
('	DearLily_XO	','	Nightcrawler looks so good cant wait to watch it	'),
('	Paul________	','	I want to go see nightcrawler this Friday but Ill probably be too tired to go after work	'),
('	yooo_antdoee	','	I want to see nightcrawler	'),
('	rahianrodriguez	','	Am I the only person who wants to see that #NIGHTCRAWLER movie... Looks so good!	'),
('	CG_3_	','	Nightcrawler looks so good	'),
('	CapsulaCinefila	','	¿Ya viste el aterrador #Trailer de "Nightcrawler" con #JakeGyllenhaal? http://t.co/m7xFp3FZzM	'),
('	Lele_rossetti	','	70mebeeijar Annabelle	'),
('	bennjeff	','	Yo how creepy does "Nightcrawler" look	'),
('	Boopsyou	','	Win! Follow CultBoxTV and RT for a chance to win 5 x Annabelle goodies - http://t.co/juijRCROVM  #AnnabelleCB http://t.co/dqpDhJ09fE	'),
('	_manderss	','	dom_bousquet we still need to see Annabelle and ouija!!!!	'),
('	lowgyy	','	I wanna go see Nightcrawler so bad ?	'),
('	jewmatic	','	Nightcrawler looks awesome	'),
('	xoxsusana	','	i want to watch nightcrawler this weekend ?	'),
('	jtwpennst8mofo	','	Dude #nightcrawler looks so damn good.	'),
('	lipstickalley	','	Bey and Jay at the Nightcrawler movie premiere in NY 10/27 http://t.co/JizcYlOdJo	'),
('	Boopsyou	','	RT ODEONCinemas: RT & follow for your chance to win goodies with #TheJudge - in cinemas now! http://t.co/c0KvIotITX http://t.co/bNotmI3fS0	'),
('	_marklz23	','	Esse Nightcrawler vai prometer ein	'),
('	jjflowers22	','	I wanna see nightcrawler when it comes out. Whos down?	'),
('	Stephbuscus101	','	Bungie Can we get a Guardians pack for DestinyTheGame? PLEASE??? #GuardiansOfTheGalaxy #Destiny http://t.co/y1FhnPBsa9	'),
('	PlacidLife_Don	','	I wanna see Gone Girl and nightcrawler soooo bad	'),
('	ashley_slovak	','	On another note I cant wait to see Nightcrawler ?	'),
('	_CameronFox	','	Really want to see Nightcrawler ?	'),
('	Jimisonny	','	CANT WAIT TO SEE NIGHTCRAWLER. WHO WANTS TO GO WITH ME ILL PAY $4.75 FOR MILK DUDS BUT WE ARR DRINKING WATER CUPS SORRY.	'),
('	EmilieMaureen	','	Anyone wanna go see #NightCrawler with me?	'),
('	PeteMMA	','	is that super creep rob lowe or jake gylenhal in nightcrawler	'),
('	perez_lf8	','	I wanna go see nightcrawler this Friday?	'),
('	ERubs09	','	I really really want to see that Nightcrawler movie	'),
('	Emmett_32	','	Whoa. New Nightcrawler trailer has Backseat Freestyle. Now thats G(yllenhaal)	'),
('	MrKooKam	','	Have you seen #CampXRay and if so how would you think about #Guantanamo #Detainee  #askTakei #UNTtakei	'),
('	tmj_asvp	','	Nightcrawler looks good as hell	'),
('	JacobGoring	','	Cant wait to see #nightcrawler	'),
('	movstages	','	Birdman or (The Unexpected Virtue of Ignorance)	'),
('	http://t.co/RutYh7vbJy Watch This At High Quality Hollywood Bollywood Movies And Downloa…	','		'),
('	lgorGomes	','	Dont get me wrong I enjoy a solid thriller as much as the next guy but Annabelle has simply run its course with me. For now at least.	'),
('	LPMc	','	Adv screen of #Nightcrawler. They ask for comments after: "Jake Gyllenhaal is overdue for an Oscar. This should be it." 	'),
('		','		'),
('	#NOTLIKELASTTIME	','		'),
('	_DRCJ_32	','	Nightcrawler looks like it will be a great movie	'),
('	triplewhopper45	','	I really want to see nightcrawler	'),
('	ThatMan_JC	','	I wanna see Nightcrawler but I feel I can already guess what happens	'),
('	bitchychick15	','	???? “BeyonceLite: Beyoncé Jay Z & Jake Gyllenhaal at the Nightcrawler Premiere in NYC http://t.co/6o08kfNKHY”	'),
('	AlfredMadril_	','	Im gonna go see nightcrawler by myself.	'),
('	J_ReeseIII	','	I want to see nightcrawler ?	'),
('	HulkingHuss	','	Three movies I gotta see is dear white people John wick and Nightcrawler	'),
('	TheFingerPoppin	','	I wanna watch Nightcrawler with someone ?	'),
('	tclessard	','	Nightcrawler looks like the type of movie that makes you aware of your boring ordinary life	'),
('	MEVeezy	','	NightCrawler looks fye	'),
('	_gmanson	','	nightcrawler just might be my favorite x-men movie!	'),
('	CincoDeMaiya	','	I have to see Nightcrawler this weekend. That movie looks amazing	'),
('	JYK_001	','	amycakesdd alontods infinity_shred fckingnate I want to see Young Ones still but also Birdman	'),
('	_KCielooo	','	Creepy Annabelle ???	'),
('	Sneadmeister	','	Yo Jake Gyllenhaal is so creepy in that Nightcrawler trailer	'),
('	AndrewB1216	','	Nightcrawler looks really interesting	'),
('	Sofia_Victoria3	','	Annabelle??	'),
('	elyssalol	','	nightcrawler looks like a good ass movie ?	'),
('	AmaurysGrullon	','	Best movie ive seen in 2014. #birdman #michaelkeaton #theenexpectedvirtueofignorance… http://t.co/F6T1zLZZBa	'),
('	DC_zhoumi419	','	heyhaena Or theres Annabelle...anything sounds good right now since its been awhile for me to catch a movie. /Shrugs and rolls over/	'),
('	jake_rsully	','	Nightcrawler looks like he has 2 personalities	'),
('	courtthecat	','	Thinking about Birdman makes me want cry but a cry so happy that the tears and smiley faces	'),
('	MTDarrough	','	Getting impatient waiting for Nightcrawler to come out	'),
('	cosmo_gmr	','	Finished reading #GoneGirl and my mouth was open for a great part of the 500+ pages... loved how unexpected it was.	'),
('	tokthadon	','	The Ferrari Sergio.  Only making 6 have to be invited to buy it.	'),
('		','		'),
('	Birdman gon pay somebody like $60 million for their invitation lmao	','		'),
('	TheFuture_SM	','	Cant wait for nightcrawler	'),
('	frugalmaniac	','	Now that you have seen the #GoneGirlMovie check out the #book http://t.co/Zp1c083AoD #follow #GoneGirl	'),
('	FranMLoChirco	','	Is it bad that I care more about the upcoming film releases than school #Nightcrawler #Interstellar #ExodusMovie	'),
('	a76514850	','	http://t.co/U1B0lIm9J3 - News	'),
('	spagh3ttio	','	Birdman was absolutely amazing. Best movie Ive seen in a long time.	'),
('	briks42	','	Jake Gyllenhall in Nightcrawler IS thedudekfc . Looks personality livelihood everything. He should get royalties.	'),
('	BillyCorben	','	Birdman is a wild ride. Like spending a long night on the town with Shia LaBeouf.	'),
('	_ShaneO93	','	Totally going to see nightcrawler	'),
('	courtthecat	','	Or tiny little Michael Keaton faces. Birdman makes me want to cry tiny little Michael Keaton faces.	'),
('	BMillzzYa	','	Who wants to accompany me and see  #nightcrawler opening night on Thursday?!?! ... movie looks amazing	'),
('	_Kylesaurus	','	I could go see Nightcrawler on Halloween night.	'),
('	ValeriaIsmodes	','	Watching Annabelle with the girls tonight ????	'),
('	LuuAraandaa	','	karmabieber01 You saw the new movie Annabelle?	'),
('	_corpacheco	','	“What would you risk for me?” “Everything.” #TheBestOfMe ?	'),
('	janeernie19	','	going to see Annabelle rn cuz last minute planning is great??	'),
('	MTDarrough	','	Getting impatient waiting for #Nightcrawler to come out	'),
('	JustAskM	','	that "Nightcrawler" trailer currently has the record for me going 100 to 0 on the excited meter. I just KNEW i was getting a Marvel movie.	'),
('	HotVideoGames2	','	New PS2 Harvey Birdman: Attorney at Law  Sony PlayStation 2 Game  http://t.co/zXq0R4FR86 http://t.co/JQHRkidA7w	'),
('	Brett_Eggerichs	','	Is this "nightcrawler" movie about the life of Charlie Kelly?	'),
('	octavia_ovoxo	','	I havent even seen Annabelle	'),
('	BestMoviesEverN	','	‘Nightcrawler’ Red-Band Trailer: Vulgar Praise Flows for the Excellent Thriller	'),
('		','		'),
('	This Nightcrawler red-band... http://t.co/9TIBOoB5wH	','		'),
('	Mrs_Yokai	','	HUBBA HUBBA *pants*. it should be illegal to make cartoon men this attractive. #BigHero6 #ProfCallaghan #conceptart http://t.co/1odTCyQ3yY	'),
('	Bringmydadback	','	Finna lay down and watch annabelle . Is it even scary?	'),
('	Honeybeebaked	','	Jake Gyllenhaal looks nasty as shit in the movie Nightcrawler	'),
('	RogueDior	','	Yass  RT hausofJazzy: “BeyonceLite: Beyoncé Jay Z & Jake Gyllenhaal at the Nightcrawler Premiere in NYC http://t.co/lVt6OZN8Oz”	'),
('	vinny_ray	','	Seeing Annabelle a few days before Halloween. Im so festive right	'),
('	Daveyy_Boyy99	','	The fact the trailer of nightcrawler has  backstreet by Kendrick Lamar as its film song?	'),
('	yaniggayanick	','	1livin im tryna see nightcrawler soon too	'),
('	StichedDoll	','	Wow. I am absolutely disapointed in VHS viral.  #vhsviral #vhsmovie the first 2 were so much better.	'),
('	DukeWilliams187	','	Birdman young thug rich homie killing da game rite now...	'),
('	not_Logan7	','	I just wanna go see Birdman with someone. The movie not the black guy....	'),
('	C_LO_22	','	I cannot wait to see Nightcrawler. Theres never been a movie like that before. So jacked. I will go alone if I have to	'),
('	ThaStretch	','	Ima catch that nightcrawler flick when it come out	'),
('	brianpja	','	Cant wait to see Jake Gyllenhaal hopping around in a skin tight blue suit for that new Nightcrawler movie!	'),
('	LilJordan396	','	Brackin in the Bentley boolin with some bitches strait bleedin..lmao square bidness birdman	'),
('	Barahona178	','	paigepfau_ Annabelle is good!	'),
('	yanni_PINK	','	“Only1Drea: yanni_PINK to see what”Annabelle gone girl & John wick	'),
('	monnykk96	','	Watch annabelle. Its not scary.	'),
('	crayselleee	','	Watched Annabelle now The Conjuring with dem cousins ?	'),
('	nahhorne	','	birdman makes me so mad	'),
('	46nascargirl	','	Its not yet #TheJudge  no jail time come on RobertDowneyJr ...	'),
('	Free him	','		'),
('	ryannummer28	','	Still havent seen Annabelle...	'),
('	paytstone	','	jake gyllenhaal with a man bun ... ugh im done ?? #nightcrawler	'),
('	ADDIS0NCALDWELL	','	I wanna see Annabelle so bad :-/	'),
('	ravenbat11	','	"Gizmodo: If you cant go see "Birdman" watch "Biutiful" on Netflix tonight http://t.co/ZxdyGIq5Y8 http://t.co/7RTixVy0iu"AndrewGrigiss	'),
('	yivialo	','	Photo: fuckyesbeyonce: Beyoncé Jay Z & Jake Gyllenhaal at the ‘Nightcrawler’ Premiere in NYC. (10-27-14) http://t.co/ltQh5pgstg	'),
('	yivialo	','	Photo: fuckyesbeyonce: Beyoncé Jay Z & Jake Gyllenhaal at the ‘Nightcrawler’ Premiere in NYC. (10-27-14) http://t.co/KlobEuTzvD	'),
('	tymepilot84	','	Around-the-World: Annabelle Rules In Mexico Guardians Passes X-Men - Box Office Mojo http://t.co/dCzwEVinRZ	'),
('	DJ_ELKING	','	Finally watched X-Men: Days of Future Past great movie one of the best X-Men movies yet! #XMenDaysOfFuturePast #XMen	'),
('	ZachNovak	','	It needs to be Friday already so I can see Nightcrawler	'),
('	ivanchoovando	','	Annabell get ready do not sleep chefarturo ( Cinépolis - cinepolis for Annabelle) https://t.co/KA2RZ1t4JB	'),
('	leopardreign	','	#TheBookOfLife IS AMAZING AND ADORABLE GO WATCH IT NOW	'),
('	fuckingpaarker	','	ANNABELLE	'),
('	ajwalker122	','	I still have no idea what the movie "NightCrawler" is about. . . but I wanna see it  #noidea	'),
('	brandonsbuzz	','	THIS BITCH IS INSANE  #GoneGirl	'),
('	Hilma_Ahda	','	Again tp versi youtube ? Annabelle (with Icut Ananda  fadilalilihdyh and 2 others) — https://t.co/zYtuDTJFPW	'),
('	JanineAldama	','	Nw: annabelle	'),
('	ChocoThunderr	','	Did he watch Annabelle before coming to work today?	'),
('	MattGarlo1	','	100% seeing Nightcrawler	'),
('	invisabelNacis	','	On repeat! Colbie Caillat. #np #TheBestOfMe http://t.co/FFFMrtgFk0	'),
('	JoePoJr	','	RT Gizmodo: If you cant go see "Birdman" watch "Biutiful" on Netflix tonight http://t.co/EwkV81HZqT http://t.co/O3aoTqybh7	'),
('	taschamendes	','	Vi Annabelle mt show rs..	'),
('	LiloneTeveez93	','	TaFuturReine Annabelle	'),
('	Amygrace0	','	okay I just got freaked out watching the annabelle trailer help sos	'),
('	coolioallie	','	i want to watch annabelle	'),
('	SelamTY97	','	adderallx Annabelle was better. the acting wasnt that good and it wasnt that scary	'),
('	matt_barton13	','	I WANT TO SEE INTERSTELLER	'),
('	CollettMeg	','	DraculaUntold was EPIC! Everyone should go see it and support truly great movies!!! One of my favs this year. B-A-N-A-N-A-S!	'),
('	susanayharry	','	karmabieber01 You are like Annabelle OMG Haha	'),
('	VegasFilmCritic	','	Fly! #BirdmanMovie — watching Birdman Movie at Regal Village Square 18 http://t.co/0YJdlxNQd1	'),
('	Shitaaa15	','	Now watch Annabelle- huu	'),
('	MissHaMiee	','	klebekahs I very sorry D: if it makes u feel better ...the movie Annabelle killed me last night	'),
('	Ester_Manning	','	#TheBookOfLife IS AMAZING AND ADORABLE GO WATCH IT NOW	'),
('	Leyanpark	','	CultBoxTV Follow CultBoxTV and RT for a chance to win 5 x Annabelle goodies: http://t.co/c2MUzxZRHF #AnnabelleCB	'),
('	ImmortalJuan	','	November 24 - rich gang album . Birdman confirmed	'),
('	AlyssaColon1	','	Omg Annabelle was a good ass movie ?	'),
('	jerneybrooks	','	Annabelle _madisonf http://t.co/CHBde3TXky	'),
('	DamnStarCool	','	Birdman prophesied my last tweet. #realshit	'),
('	arianadestyless	','	Harry_Styles want to go see the movie annabelle with me? :P	'),
('	Beyonce_Brz	','	Beyoncé Jay Z e o ator Jake Gyllenhaal na Premiere do filme Nightcrawler 	'),
('	em Nova York. 	','		'),
('		','		'),
('	#PrettyHurtsEMA http://t.co/99oxuvBrTI	','		'),
('	canernarr	','	Annabelle was actually exciting oh man...	'),
('	SRDtv	','	WOW RT ImmortalJuan November 24 - rich gang album . Birdman confirmed	'),
('	wholabae	','	yassss muthaaaa RT BeyonceLite: Beyoncé Jay Z & Jake Gyllenhaal at the Nightcrawler Premiere in NYC http://t.co/U53jbyHRhT	'),
('	_corpacheco	','	“BestOfMeMovie: You cant put an expiration date on true love. #TheBestOfMe http://t.co/6ziRww5pOm”	'),
('	GoGetta131	','	“thatD1FFdude: ????????? 3shots in!! ...and this movie is like 2hours long” birdman hand rub ???	'),
('	fvckhails	','	Fuck whoever said Annabelle isnt scary	'),
('	weirdomarlins24	','	valerianaaaxx annabelle	'),
('	MikeyMikeee99	','	So whos gonna be my date to watch #Nightcrawler Friday??	'),
('	amaloia	','	OMG! OMG! !  O. M. G.  Thats all I can manage to say after #bighero6 #scad #SAVFF	'),
('	evianarizka	','	Annabelle bae .wkwk (with Rika ananta and 7 others) [pic] — https://t.co/tPmiR0dVkh	'),
('	ItsCrystal_Bear	','	Im such a wuss i was freaking out durning Annabelle	'),
('	TysharaBlouin	','	finally watching Annabelle with the kids.?	'),
('	RobbyRav	','	new #HubbieTunes as i eat stuffing. yes yes yes. RT OGJOHNNY5: Rich Gang 2 is coming November 24th according to Birdman on Flex show.	'),
('	Tr_Silveira	','	ingridscholantt kkkkkkkkkkkkkkkkkk annabelle te assustou	'),
('	Jay_Wyse	','	So this why Nicki album got pushed back? RT OGJOHNNY5: Rich Gang 2 is coming November 24th according to Birdman on Flex show.	'),
('	teraaakt	','	stomperchick but it was soooo good! 	'),
('	Im tryna get my way outta scary movie ?? but yes lets go watch Annabelle ?	','		'),
('	Canada33_Nelson	','	That elevator scene was hilarious!!! ? #TeenageMutantNinjaTurtles	'),
('	sofaa_arias	','	ENCONTRE UN LINK PARA VER ANNABELLE. ME FUCKING AMO.	'),
('	Made_InTokyo	','	Did Birdman get charged for that molestation allegation yet or nG?	'),
('	NYDNEntertain	','	Bruins legend Cam Neely says he will be in #DumbandDumberto http://t.co/0JT91VTRLg	'),
('	cvegnad	','	CAN --> enter to win #BigHero6 swag from #SubwayAndAMovie ! http://t.co/SI6gZo6Rwp	'),
('	soymilla	','	ReplyKoba pqbielzinho annabelle	'),
('	Izzy_ohsopretty	','	? RT BeyonceLite: Beyoncé Jay Z & Jake Gyllenhaal at the Nightcrawler Premiere in NYC http://t.co/lQ6k3GB8TS	'),
('	YeCgoST	','	‘Birdman’: Unforgettable film with beautiful baggage 	'),
('		','		'),
('	           http://t.co/dvlb3ZqOF5	','		'),
('	kimbermyers	','	Id say that every film should be as much fun as #JohnWick but then Id never leave the theater. http://t.co/MnxGZ73aBe	'),
('	iLoveshawn5000	','	Were not worthy  RT OGJOHNNY5: Rich Gang 2 is coming November 24th according to Birdman on Flex show.	'),
('	Maddkitty758	','	Annabelle....??	'),
('	abarcaa_	','	abarcaems Annabelle next headass	'),
('	EskobarSanchez	','	RT ThatPersianGuy: My body is ready. RT OGJOHNNY5: Rich Gang 2 is coming November 24th according to Birdman on Flex show.	'),
('	ComplexMusic	','	The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	JordanSenpai	','	Why Birdman always look like he starring in a new hand lotion commercial?  #SouthsideEdits https://t.co/NL9Uz4uRBo	'),
('	astrolodaddy	','	gksk_1 this nightcrawler confuses me cause its not about kurt wagner wtf???	'),
('	AaronDLT	','	Nightcrawler looks dope	'),
('	citraprmts	','	Watching Annabelle — https://t.co/6nTaWdHzbh	'),
('	Tilly_Hardin	','	That elevator scene was hilarious!!!  #TeenageMutantNinjaTurtles	'),
('	NatalieRunion	','	While mommy leads worship Annabelle practices her method acting on the iPad...#whatshermotivaton http://t.co/Af4QknjArN	'),
('	DonavanBenz	','	"Annabelle next"	'),
('	OjManeLaFlame	','	Probably get push back too lol RT Salastheboss: Birdman sliding Nicki and Wayne over for that Richgang Album. Nov 24	'),
('	Ace_IOD	','	Chillin w the homie kidglorymusic at Bowlmor Lanes Lit asf #IOD #NightCrawler	'),
('	BamagedDrain	','	Great cameo by RealKevinNash in the movie #JohnWick. His Russian accent was too sweet!	'),
('	ImTheBoysGirl	','	"KStewartINA: Photo: Love this Sundance Portrait! ? #kristenstewart #sundance #campxray http://t.co/iTtwQkuWPt"cool girl	'),
('	boehnjamin	','	Cannot wait for the movie Foxcatcher to come out. Steve Carell looks magic and based on a true story. Sports bio dramas usually kill it	'),
('	IRockKswiss	','	RT EskobarSanchez: RT ThatPersianGuy: My body ready. RT OGJOHNNY5: Rich Gang 2 is coming November 24th according to Birdman on Flex show.	'),
('	MattMannall	','	Radio Birdman on DoubleJRadio  Yeah Hup!	'),
('	moviemikericci	','	There wasnt any doubt.	'),
('	I rated Birdman 10/10  #IMDb #keaton http://t.co/bb5Ilgf93J	','		'),
('	puprocker5	','	#earworm for today:  "I Will Wait" by #MumfordandSons -->twas very endearing when Manolo sang this to Maria in #TheBookofLife film animation	'),
('	CrystalCo530	','	Annabelle was a hoot. Kicked back. Ate a pretzel.	'),
('	djredcup	','	? RT OGJOHNNY5: Rich Gang 2 is coming November 24th according to Birdman on Flex show.	'),
('	BruhhMan1	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/r371YApChK	'),
('	HeyyNikka	','	The girl working at Dicks wanted Jareds penis real bad. But nope nope. Cant have that Ill #JohnWick you.	'),
('	QuanJ_5	','	That Rich Gang mixtape got Birdman thinkin he can hop on tracks again ?	'),
('	nathan_2raw	','	Date night with the mrs. #iminlove #loveoflife #johnwick http://t.co/aErNHmE3Ub	'),
('	robt77	','	Looks like BIRDMAN is finally opening in Madison at sundancemadison on Fri w/ sneak preview Thurs. Cant. Wait.	'),
('	JazmiaElan	','	Tryna see what this Richgang mixtape is about. Yall throw Birdman so much shade but I wore "Like Father like son" out n high school.	'),
('	ninemilli_	','	RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	Jess_01	','	PSchwarzenegger Annabelle	'),
('	jasminligsayy	','	NW: Annabelle http://t.co/V6Kwib0oXH	'),
('	abarcaa_	','	I wouldnt see Annabelle Im too scared?	'),
('	jperchy10	','	About to watch Annabelle in the lounge... not about the scary movie life though ?	'),
('	XMenNewz	','	New Featurette Focuses On Bringing The Two Eras Of #XMen Together http://t.co/25WdlrhcKc #XMen #XMenDaysOfFuturePast #BryanSinger	'),
('	ThaRealPchopz	','	RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	kingmarack	','	"ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman." http://t.co/0PH8SgyChD	'),
('	JohnDukesJokez	','	Is the thing in #BigHero6 supposed to look like a court molestation doll?	'),
('	Gabestaybased	','	JulissaBangz I cant find the Annabelle vine ?	'),
('	homovikings	','	barack obama is gonna make a great nightcrawler	'),
('	benwitte	','	Im at Embarcadero Center Cinema for Citizenfour in San Francisco CA https://t.co/EyCwjTSAh6	'),
('	SuckaFreeTee	','	RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	MaribelMoreno26	','	fragadoeee Me gusta! Maybe Ill do the same puedo ser Annabelle	'),
('	DrewDietsch	','	My review for JOHN WICK. Spoiler alert: this movie is AWESOME. http://t.co/46knFoN9Co #JohnWick	'),
('	xabbysos	','	Im at Annabelle & its scary	'),
('	gregslim	','	????“Timmaaay_ “OGJOHNNY5 Rich Gang 2 is coming November 24th according to Birdman on Flex show.””	'),
('	pantsRcuffed	','	How Birdman orders at McDonalds https://t.co/wHCuUu3Oeh	'),
('	JazmiaElan	','	*does Birdman handrub*	'),
('	heyhaena	','	DC_zhoumi419 oh! I heard Annabelle was good. *nods quickly* I think the last movie I saw in theaters was Captain America... Maybe.	'),
('	abake6	','	How many push backs? RT ThaRealPchopz: RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	Mrs_Yokai	','	Very dapper #Yokai poster from #BigHero6 http://t.co/Xa4XVI7lPo	'),
('	Claririlu	','	Annabelle ?	'),
('	QSquinney	','	Jake Gyllenhaal surprises ‘Nightcrawler’ moviegoers in 3 different states in 1 day http://t.co/JlQjRPf5mH	'),
('	DoubleJPlays	','	Radio Birdman - Aloha Steve & Danno [12:47] http://t.co/BU266OfdLJ	'),
('	abarcaems	','	“abarcaa_: I wouldnt see Annabelle Im too scared?” thats why Andys coming	'),
('	blackNfineee	','	fck_THAT we finna go see Annabelle ?	'),
('	Lstarroon	','	Scaring my housemates after watching the Annabelle film ??	'),
('	rustyweston	','	Kudos to the team behind #Birdman. If a better movie comes out in 14 Ill be very pleasantly surprised. Keaton Norton rock	'),
('	toyhypeusacom	','	#Target Exclusive #TeenageMutantNinjaTurtles Leonardo Evolution 3 Pack http://t.co/wsyb8oHO10 #TMNT #PlaymatesToys http://t.co/uAfE6jMJyP	'),
('	Bergyonce	','	50 cent is at the Nightcrawler movie too. I wonder if Bey will pop off on him again ??	'),
('	LissetNajera22	','	ferrealtho that was scarier then Annabelle. ?	'),
('	DatLe	','	That Nightcrawler movie is confusing. I didnt make the X-Men connection. But my coworkers did. But now apparently its not about the mutant	'),
('	paigekearneyy	','	Going to the cinema tomorrow night to watch annabelle and Im already shitting myself	'),
('	CreativeNotez	','	I seen rich homie and birdman..... But who is the chick wit them????? J/s ....lmao! http://t.co/qDcB39YWZV	'),
('	defafarizan	','	??? ? Annabelle (with MIA-2?) — https://t.co/SctK2orUcT	'),
('	MalikZMinaj	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” ARE YOU FUCKING FORREAL	'),
('	fayemacatangay_	','	Annabelle ?	'),
('	blaaake_renfro	','	lindsey_malonee colechandler497 what are you doing Birdman?	'),
('	shelby_harty	','	birthday cupcakes I hid and forgot about in August showed up on the counter today and nobody knows how #annabelle??	'),
('	Mystical_Gift	','	_FallenBeauty *Annabelle let out a heavy sigh and looked at the time. She grumbled* Who the hell calls at such a late hour. *She looks -	'),
('	kaiofhearts	','	#GuardiansOfTheGalaxy by myself yoloooo	'),
('	putri_putpita	','	Watching Annabelle — https://t.co/pqdMEkA9WR	'),
('	onikasbae	','	KEEP IT. “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	NickiMinajsus	','	LMAOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	_heykassyy	','	jorgeluisg4 really? Damn. Have you seen Annabelle?	'),
('	BeyonceBrasil_	','	Beyoncé Jay Z e Jake Gyllenhaal na Premiere de "Nightcrawler" em Nova York. http://t.co/RAuuqyLTkh	'),
('	OGxmillz	','	this is a joke. RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	JahMari_Couture	','	SEE.. ? RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	StanfordClark	','	Cool #BigHero6 poster from France. Oui! 11 days. #MeetBaymax http://t.co/ogSFYjkzNr	'),
('	heen_Doggish	','	RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman. http://t.co/Xa9pVKmSKW	'),
('	frugalmaniac	','	Its a  #Groot thing! http://t.co/hSlTlzlzoe #Marvel #GuardiansOfTheGalaxy #toy #awesome #follow	'),
('	jtwilliams923	','	If you want to see someone get shot and punched at the same time #JohnWick is the answer!	'),
('	DemYAnksSquare	','	APMike "AP MIKE the Bayonne Nightcrawler" a role you were born to play	'),
('	paolocase	','	HARVEY BIRDMAN ATTORNEY AT LAW: OR THE UNEXPECTED VIRTUE OF IGNORANCE: Or we are all the best and the worst people when were alone.	'),
('	prettyboyferd	','	Birdman need a stop this Rich Gang pipe dream and liberate a new BIG TYMERS project!	'),
('	aleemartiinez19	','	NickolasBosco a ver annabelle u.u	'),
('	BozzLughtyear	','	“ChrisNeal1134: I really wanna see Nightcrawler.”!!!!	'),
('	Cinemalinks	','	4. #GoneGirl $11.1M: Play Trailers http://t.co/lnxNZ26yPZ	'),
('	xabbysos	','	Im at Annabelle & its scary af	'),
('	TeamMinajQueen	','	Tell the bird we dont want it RT “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	shaundavid	','	LaurenShultis If this person does not walk around saying "I am Goot" all day Ill be supremely upset. #GuardiansOfTheGalaxy #Marvel	'),
('	Taja_Doee	','	"ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman." Fuck him Nicki album drops that day wtf	'),
('	MINAJAYSTY	','	GET THE FUCK OUTTA HERE BYE RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	elianaelianam	','	Is nightcrawler not playing by my house?! WTF! IM SO UPSET RIGHT NOW.	'),
('	GrantDaGenius	','	2 days after my b day “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/oIpyfWmFu5	'),
('	Francineludels	','	shit annabelle	'),
('	chloe_z12	','	when ur watching annabelle with ur brothers and u almost poop all ur pants	'),
('	Ntakibazo	','	Thank you to the makers of citizenfour. And to Edward Snowden and the other person for making it possible. This fight has only just begun.	'),
('	ThatStalkerAnna	','	MiaLouisePerez_ hello Im Annabelle but call me Anna -smiles-	'),
('	Snooks_YO	','	Annabelle	'),
('	mjndotcom	','	“octavia_ovoxo: I havent even seen Annabelle”me either ? movie date	'),
('	TheGracinator	','	I just checked in on IMDb. #XMenDaysofFuturePast #cinephile #Wolverine # http://t.co/TjnyKvJllz	'),
('	Vickayyyy	','	"Are you satisfied with your care?" #BigHero6 savfilmfest #SavannahFilmfestival #Incredible #Always #love	'),
('	TatiLovesOnika	','	OH BITCH. I KNOW THEY DIDNT. “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	Scandalous_Mimi	','	I used to sleep on Jake Gyllenhaal as an actor but MAN. That boy good. I wanna see NightCrawler ??	'),
('	coachs_problems	','	Blond_Teacher is home!!! Yay!!! #GoneGirl returned.	'),
('	ChristBustos	','	#Cine Annabelle	'),
('	AnthonyMinaj_	','	Of course it is. RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	Ema_Hudson	','	Ouija more better than Annabelle I guess?	'),
('	FollowRoyalty_	','	Girl what RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	ILScreenings	','	Free Advance Movie Screening of Nightcrawler (SeeNIGHTCRAWLER) in Chicago IL via LatinoScoop (Contest) - http://t.co/WEddOkGzVy	'),
('	narnold15	','	Time to watch the movie Annabelle...	'),
('	AlmightyJosh_	','	Im a hotboy like a Birdman ??	'),
('	JAndreCoello	','	... “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	abarcaa_	','	DonavanBenz is ok you can touch elbows during Annabelle???	'),
('	CaliforniaBarb	','	Is birdman fucking serious lol	'),
('	TylerLewinsky	','	youve got to be fucking kidding me. RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	AtiqahRaudhah	','	Done haha annabelle best	'),
('	Ramzy_CR7	','	Annabelle #lrt	'),
('	Putriseraaa_	','	Classmates gone mad watching Annabelle and they can scream at any moment rn so heres a selfie  SMP… http://t.co/tfP1kHtcgB	'),
('	50ShadesOfPetty	','	Dont upset me..... RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	NasifahB	','	Just watched annabelle!	'),
('	KlyseZolanski	','	Are you fucking serious. RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	TheNerdsPodcast	','	Our new episode "Pat Cant Say Tusk" is now available! #GoneGirl #Shocktober PromosForAll http://t.co/UP5GSxhRmp	'),
('	ksInfamous	','	“JahMari_Couture: SEE.. ? RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” ???? tf!?	'),
('	STAR_1day27	','	_Cnajai lol smh and actual movie woman!! ???? Annabelle	'),
('	chrisjrosen	','	Wonder if Beyonce and Jay Z love "Nightcrawler" as much as I do.	'),
('	Mrs_Yokai	','	Hiros smile reminds me so much of my stepbrother here lol #BigHero6 #HiroHamada http://t.co/pFCUOXRBM8	'),
('	OLLIERELOADED	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/N3fvHXsbtG	'),
('	cvntnika	','	BOY IF YOU DONT GEY “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	KenInTheTrap	','	oh i get it RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	kazz_12882	','	WE DID NOT GET PUSHED BACK FOR THIS. RT “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	jtwilliams923	','	If you want to see OfficialKeanu stab someone with a knife that said someone is holding #JohnWick is the answer!	'),
('	its_michellexD	','	The best of me was definitely one of Nichols sparks best movies??????? #TheBestOfMe	'),
('	LexiBritt1295	','	Had a great night with my boo her mama and ma! #theBestofMe #boothang #girlsnight	'),
('	ksInfamous	','	“JahMari_Couture: SEE.. ? RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” ? it’s true	'),
('	YungChad	','	Lotus__Noir cool me too. *birdman handrub*	'),
('	DathomirShaman	','	Just got my #GuardiansOfTheGalaxy #TylerStout #Mondo  print back from the framers. So much glory! http://t.co/sLpUfbGM5n	'),
('	SouthSide_404	','	Ugh got movie on pause ish me Annabelle got me twerk  over herr	'),
('	nickicomments	','	goodbye. RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	NMLite	','	RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman. < http://t.co/SgI57OPvsG	'),
('	austinsboner	','	austinsboner aye lmao when Austin was possessed by Annabelle	'),
('	MinajNC	','	Biiiiiiiiitch..... ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman. http://t.co/F63Uu6WjTA	'),
('	Cantouchthekid	','	OOOO so its Birdman catching these licks “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	joaniemaloney	','	Birdman was a feat (performance & technically) but for me it was like Synecdoche New York in that its not really my type of movie.	'),
('	KenInTheTrap	','	Well all be too busy crying. Move RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	msstacey22	','	RT BeyonceLite: Beyoncé Jay Z & Jake Gyllenhaal at the Nightcrawler Premiere in NYC http://t.co/qcbPlGwh85	'),
('	softnoir	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/b5EAkSbsfu	'),
('	KissesofGodiva	','	Needed a break from men? Letoya lemme help with that! *Birdman handrub*	'),
('	macymcgairty	','	I want my own Dawson Cole! #TheBestOfMe #TheBestOfMeMovie	'),
('	jtwilliams923	','	If you want to see OfficialKeanu get thrown off a balcony #JohnWick is the answer!	'),
('	kisssmandy	','	Found a new serie that could be interesting. Jareds friend is in it though Annabelle. And the accents are kinda.. idk. But Im hooked now.	'),
('	Bohmpresents	','	See eddieizzard the #lostpython when he brings his #ForceMajeure tour to Aus & NZ in 2015. https://t.co/ekV5zUaAzs http://t.co/dnEDDJbiZN	'),
('	WatchMyThron3	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” ?????	'),
('	Nicki4LifeTM	','	hmmmmmmmmmmmm RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	yourstrulyAbhi	','	#TheJudge Best film coming out of Hollywood this year. RobertDowneyJr was elegant. Sir Robert Duval at his usual Best.	'),
('	iambradds	','	Are they serious? I... RT ComplexMusic The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	jtwilliams923	','	Go see #JohnWick!	'),
('	itzbarbieb_tch	','	K. “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	StassMarley	','	I know they did NOT PUSH MY BITCH BACK SO YOUNG THUG RICH HOMIE & BIRDMAN CAN RELEASE SOME BULLSHIT	'),
('	FineBvrbie	','	Ummm. RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	RAFIZUS	','	IF THIS IS WHY TPP GOT PUSHED BACK IM UNSTANNING RT ComplexMusic: The “Rich Gang 2” album will be released on Nov. 24 according to Birdman	'),
('	biebersthrill	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/TgUoSOP8Oh	'),
('	TylerLewinsky	','	if im being honest I had no idea birdman was even making music still I thought he was in jail for killing someone	'),
('	HausOfAustin	','	CTFU RT ComplexMusic The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	NadixNika	','	Nobody cares about Birdmans album. :(	'),
('	fergienewz	','	IM SCREAMING. “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	LEGENDARYJOJO	','	REALLY NIGGA?1?!?!?!?!?!??!?!?! "ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman."	'),
('	amybwilliamz	','	holy mother of Annabelle and Joseph on Jesus h Christ lets dap it up *shoots heroin*	'),
('	jacquelneramos	','	Im gonna go see Nightcrawler with Michael tomorrow and Im pumped as hell because I havent seen him since he graduated in 2013.	'),
('	FreeNewsPos	','	(((((((CACAR))))))) =;=Nightcrawler=;= Full Movie 2014 Online Free HD (((((((CACAR))))))) =;=Nightcrawler=;= F http://t.co/QEY34UtlTO	'),
('	Jaacy_11	','	I wanna see Nightcrawler so bad	'),
('	aalaysiasus	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” Yall pushed Nics album back for this?! K.	'),
('	DanFranklyn18	','	HuelDaddy go see Annabelle.	'),
('	TheTimSnyder	','	#JohnWick. Lets go Keanu.	'),
('	HypeGreen	','	#JohnWick I wanna watch that	'),
('	NadixNika	','	“StassMarley: I know they did NOT PUSH MY BITCH BACK SO YOUNG THUG RICH HOMIE & BIRDMAN CAN RELEASE SOME BULLSHIT” LIKE. ?	'),
('	slightlysubtle	','	Cant stop thinking about Birdman. Absolutely incredible. Seriously thinking about seeing it a second time at the theatre.	'),
('	ShawnMinaj	','	Wut??? RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	softnoir	','	lmao fuck birdman.	'),
('	smapine	','	amazon:LIVE BIRDMAN [VHS] http://t.co/m92PiL3emS #SMAP #????	'),
('	LOOKINFORAMINAJ	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/bWMUgXtw8L	'),
('	OliviaKrieger	','	Annabelle was super predictable	'),
('	SkinnyCartman_	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” ??	'),
('	TrillyTuesday	','	BRICKSLOCAL actually couldve benefitted from some more birdman verses	'),
('	kylepinion	','	jessidee morphemes wakingthedead17 mleecook Jwmaldonado ConnorLesniak spinaret well prob see Nightcrawler I imagine.	'),
('	BiebersVicky	','	I just saw #Annabelle  she wants your soul...	'),
('	_ObeyT	','	Please Let This Be A Joke?? RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman."	'),
('	Lstarroon	','	Im going to purposely buy this and put it in one of the housemates bedrooms at night #Annabelle http://t.co/g2dgpvqnh6	'),
('	JavianMinaj	','	I hope everyone who releases on that day flops ComplexMusic: The “Rich Gang 2” album will be released on Nov 24 according to Birdman."	'),
('	asvptay	','	I wanna see that movie nightcrawler	'),
('	NakocheeKim	','	just finished hearing #Annabelle from the other room ? #TrueStory	'),
('	golfwangxo_	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/nXz1dhig0v	'),
('	BeyLites	','	Beyonce Jay Z and Jake Gyllenhaal at the Nightcrawler Premiere in NYC. http://t.co/NguXYKtCLg	'),
('	lizinthelibrary	','	Annabelle is sick. kitaq is sick. #babylife http://t.co/QAJJVBbB22	'),
('	LOOKINFORAMINAJ	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/RJHslvZMtY	'),
('	mechvnicdummy	','	Forgot there was a first “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	V_LuvsMusic	','	niall and louis in ANNABELLE ?????? https://t.co/OPoJrJWqxN	'),
('	KrishOza	','	Well thats definitely not what I expected! #GoneGirl	'),
('	Harri2G	','	Birdman that nigga on every track  until he start rapping	'),
('	Alie_Capobianco	','	“ayylmao: Bruh this beat fire ??? http://t.co/FX0haLiuY2” just shit myself because I saw this while watching Annabelle	'),
('	engy_rehim	','	Ahmed how did sleep at night :D — watching Annabelle	'),
('	lncoolj	','	"Soooo me and Adrienne decided..."	'),
('	#GoneGirl 	','		'),
('	#GoneLeon 	','		'),
('	#dictatorship? 	','		'),
('	chantzzz adrienne55	','		'),
('	JheeFrancis_	','	oi annabelle is rahhhh scary fr??	'),
('	MadeforMinaj	','	Really though... RT NadixNika: Nobody cares about Birdmans album. :(	'),
('	myxfusiondrink	','	on the verge of breaking free i think nicki is leaving YM too i hope birdman pushback her album for the date for rich gang 2 album	'),
('	kenziekamm	','	Cant you wait for that new horror movie?! 	'),
('	Said no one named Kenzie Bristow ever! 	','		'),
('	#annabelle #oujia ??	','		'),
('	MadisonSwinemer	','	I kinda wanna go see annabelle ?	'),
('	slowestmagic	','	Its if Ted from Bill and Teds Excellent Adventure actually went to military school. #JohnWick #Keanureeves	'),
('	NasifahB	','	Just watched annabelle!	'),
('	JenniferCNP	','	First Love Memories?  #TheBestOfMe Prize Pack ( includes $25 gift card) #giveaway jumpinbeans09  http://t.co/sYjcr5Qv51	'),
('	Dottman00	','	Nightcrawler needs to come out already	'),
('	La_Cunt_	','	Lying in bed watching annabelle and wondering what happened to horror cinema? #TheNotebookWasScarier	'),
('	EvelTed	','	Nightcrawler looks REALLY good. #RawCommercials	'),
('	megs_532	','	ready to ball my eyes out at Annabelle?	'),
('	Z_A_E	','	Nightcrawler look so good to me	'),
('	ProudEchelon	','	Just saw #TheBookOfLife w the kiddies! Such a cute movie! Definitely a keeper. ? This part made me giggle! ?? http://t.co/y3djIVHIRv	'),
('	dendenms	','	Watching Annabelle last night made me have two nightmares in a row. #script #ideas	'),
('	TrendStyleDaily	','	Gyllenhaal went hungry on purpose for Nightcrawler	'),
('		','		'),
('	And his performance is getting major notice.	','		'),
('		','		'),
('	http://t.co/SGmG4RV4qU	','		'),
('	BreeziNUrMouth	','	“Made_InTokyo: Did Birdman get charged for that molestation allegation yet or nG?”	'),
('	CS7_TKOTW	','	Nightcrawler looks good hope it doesnt dissappoint when i go watch it.	'),
('	postnebulous	','	Via nprnews: Ed Norton On Birdman Wes Anderson And Why $40 Makes Him Proud http://t.co/yuoYjP4P2c every once in awhile I love love #NPR	'),
('	R_Dizzy	','	that movie "Nightcrawler" looks dope might check that out	'),
('	Julien_XV	','	Conjuring > Annabelle.	'),
('	OnikaThot	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” WHAT THE FUCKING FUCK.	'),
('	IDESERVER8	','	LOL"ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman."	'),
('	simmerdownsirX	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/dkq2ERKGBJ	'),
('	drolexx	','	I wanna see that movie Nightcrawler	'),
('	Chilly_Willy_7	','	I really wanna see Nightcrawler	'),
('	Facebooklnc	','	Ben Affleck is answering your questions about his new film #GoneGirl on his Page now: https://t.co/nPZhlfqzQi	'),
('	ThomsonX	','	Have annabelle on my laptop but am to scared to watch it masel ha wit a cock	'),
('	BeYONus	','	TBH > RT“NadixNika: Nobody cares about Birdmans album. :(”	'),
('	SirSquirrelz	','	Nightcrawler looks like the type of film Id see on YouTube made by some Machinima partner or something. Not that thats a bad thing	'),
('	Slay_4_Nicki	','	What birdman do?	'),
('	OTRdotcom	','	Video: Rich Gang Ft. Birdman Young Thug & Yung Ralph “Riding”   http://t.co/yLjBxmsiQ3  #birdman	'),
('	carlafariasomg	','	Annabelle	'),
('	LanceRylan	','	Lololololololololol ? RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	jezmelo	','	Watching The Conjuring for the first time so that I can watch Annabelle tomorrow. I dont know why I do this to myself.	'),
('	StassMarley	','	they doing this cause they know Birdman gone need the sales more.	'),
('	NicsHeartBeat	','	THEmale_madonna KingKillerBee . Tell me why they pushed her album back for Birdman flop ass album !	'),
('	jadabradley	','	"Pelvic sorcery" - I finally saw #GuardiansoftheGalaxy	'),
('	NadixNika	','	When youre listening to Well Be Fine & get to Birdmans part http://t.co/wXz8mr9XHP	'),
('	EmilyButkus89	','	I wanna go to the movies 	'),
('	#ifistay #DraculaUntold #GoneGirl #Fury #johnwick	','		'),
('	Ch_aLda	','	Annabelle x Chucky woahhh that might be awesome	'),
('	Harri2G	','	Birdman be sounding cool as shit when he be talking on the tracks ..	'),
('	_Emmitt	','	RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman. http://t.co/NPy4TE1ZnL	'),
('	bobsaget72397	','	The “Rich Gang 2” album will be released on November 24 according to Birdman.” Yall pushed Nics album back for this?! K.	'),
('	SoSlick2Clutch	','	Nightcrawler  looks like its gone be a good movie >>>	'),
('	_Vonnoel	','	Ikhayee yah iam all ready to watch that Annabelle	'),
('	Rowan_Houston	','	Birdman announced Rich Gang 2 what a blessed day.	'),
('	lil_grezie	','	“BeyonceLite: Beyoncé Jay Z & Jake Gyllenhaal at the Nightcrawler Premiere in NYC http://t.co/3cO85GsGZA”friendship goals.	'),
('	Beautifully_Bii	','	i still waanna see annabelle	'),
('	DougieLykJBiebs	','	I saw Annabelle yesterday	'),
('	KINGontheThrone	','	Excuse me? RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	Pat_Geezy	','	Birdman dont care about no one but Young Thug right now bruh	'),
('	_Emmitt	','	RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman. http://t.co/DJnnEqDD6J	'),
('	cthagawdess	','	bruh #JohnWick was so good.	'),
('	CedricAlaska	','	“Z_A_E: Nightcrawler look so good to me” on life	'),
('	iHeartJames	','	WHO GIVES A FUCK!!!! RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	TV__agent	','	Int’l Box Office FINAL: ‘Happy New Year’ Uncorks Record Bollywood Bow; ‘Annabelle’ Still A Doll With $26.2M; ‘Lucy’ Outmuscles ‘Hercules’...	'),
('	ScreeningsDC	','	Free Advance Movie Screening of Nightcrawler (SeeNIGHTCRAWLER) in Washington DC via 43KIXDC (Contest) - http://t.co/QkvQHtZmBF	'),
('	beniam17	','	I was watching #DraculaUntold  like ??	'),
('	Nicki4LifeTM	','	asdasdasdasd RT NadixNika: When youre listening to Well Be Fine & get to Birdmans part http://t.co/OdiXZ4C1ag	'),
('	niqqquee	','	Watching Annabelle again!?	'),
('	philgubert	','	There were 16 year olds in my showing of CitizenFour! The MPAA is the worst. Thanks for being awesome IFCCenter	'),
('	bcsorexia	','	indomxtable Im about to watch Annabelle and Im scared lol.	'),
('	KidZolanski	','	Im so sad rn omfg???? RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	reggiemartin00	','	Jlaut31 yes very exciting *rubs hands like birdman*	'),
('	SkylerWolfe6	','	My nana and I were in theater 6... Watching Annabelle.... And we were the only two in there.... Talk about creepy.	'),
('	gemlufrangco	','	Watching Annabelle! ?	'),
('	Mystical_Gift	','	_FallenBeauty *Annabelle froze. Her heart pounding as she swallows nervously. She looks at her phone as her breath shakes. She sits up -	'),
('	hot1061	','	Havent seen the Annabelle Movie Yet? 	'),
('	1. Post #ILikeYourDoll in the comments below. 	','		'),
('	2. Inbox us a good call... http://t.co/T7Rslq70yS	','		'),
('	iCobiRozay	','	"ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman."	'),
('	softnoir	','	“Slay_4_Nicki: What birdman do?” http://t.co/t9XvRqNzmM	'),
('	wishaNICaWOOD	','	court_maresca Annabelle??	'),
('	kazz_12882	','	For Birdman though... Like.... http://t.co/10JSTNA4Ee	'),
('	U_go_JENNcoco	','	Annabelle doll is scarier than not getting into college	'),
('	Trent_Warner	','	#Ignorance#Character Review: Birdman or (The Unexpected Virtue of Ignorance): Co-write... http://t.co/pIBn8yJUls #CharacterLeader.com	'),
('	Joannalangfield	','	Nightcrawlers fun but Jake Gyllenhaals seriously sensational. http://t.co/PtGxfzTDBP	'),
('	ECFRIGHTNIGHTS	','	:-) — watching Annabelle	'),
('	Ikhayee	','	_Vonnoel haha okay will text u nalang if i have a copy na hahaha me want mcnee to watch tell him that he must watch annabelle hahaha! ???	'),
('	wmthesecond	','	Nightcrawler looks kinda nice. Gonna have to go see it ?	'),
('	NikkiChristie	','	Hell. Yeah. #birdman  Arclight Cinemas Hollywood http://t.co/C6VJrq1RGl	'),
('	valleym7	','	Tonight Ill watch Annabelle. 	'),
('	Tomorrow Im watching Ouija.	','		'),
('	joshuajosey	','	What a #great night #FrightWorld now at the #movies for #annabelle #TeamNoSleep #ProbabyGonnaCry with Katie3423 DaveJoeZ and diezyocho	'),
('	MarajDreamz	','	Ok see this is where the problem begins ? RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	nickislaystbh	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/ItJTBACgeK	'),
('	minajxknowles	','	Oh well. RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	___livinglegend	','	Birdman got a thing for suspect feminine niggas first Wayne now young thug ..	'),
('	TheAlekna	','	"Slingin rocks up and down the block. Shawty comes to me lookin for the flock." #birdman #yayo	'),
('	exofngirl	','	Nobar annabelle haha~ http://t.co/fKcWr881ig	'),
('	CalogeroAby	','	I want to go see #Nightcrawler on Friday!?	'),
('	BigCPDX	','	JessieLandes wheres nightcrawler when we need him	'),
('	YouLoveLenaa_XO	','	#GoneGirl was soooo good!	'),
('	MarajDreamz	','	Neaux > RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	iCobiRozay	','	"ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman."	'),
('		','		'),
('	BULL FUCKING SHIT. !	','		'),
('	SirDesmondJae	','		'),
('	LOOKINFORAMINAJ	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/SgXRWWitdb	'),
('	blainems	','	Date night at The Nightcrawler premiere with Jake himself in the room featuring Beyonce Jay Z 50 Cent and Michael Shannon. #what?	'),
('	The1andOnly128	','	The1andOnly128 Look  I not right birdman	'),
('	jessica_lynnxo	','	#GoneGirl with the rents & _RyanHawker_ ??	'),
('	___livinglegend	','	Wont be surprised if one of these days a video of Birdman and young thug kissing appear on the Internet.	'),
('	TheKidThatRaps	','	BIRDMAN GOES SO HARD.	'),
('	DontTestDaKidd	','	??? RT"ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	_Emmitt	','	RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman. http://t.co/fa28e0P8G1	'),
('	HillStreetViewz	','	#BigHero6 is in 3D?! I demand a refund! Oh wait.... #4gotiamacritic	'),
('	AgusDSG	','	Annabelle nigga http://t.co/dnAiUAbNFH	'),
('	ZeeMaraj17	','	WOWOWOWOW “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	ashhhkasa	','	annabelle with KristenMorann & ashley.... only ones in the theater ?	'),
('	TaeeMinaj	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/dQAADOqGVU	'),
('	Gleaux_	','	didnt they JUST release an album? foh "ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman."	'),
('	DontTestDaKidd	','	WOTTICE RT"ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	Awilka06	','	Crying !!! ????? I wanna see #Nightcrawler	'),
('	beezinthetraps_	','	RT ComplexMusic The “Rich Gang 2” album will be released on November 24 according to Birdman. http://t.co/9LbPZuwdxv	'),
('	jessicaxmcmahon	','	Were alone in the theater for Annabelle. ? adamslutz	'),
('	nathanialjg	','	If we dont get into Birdman tonight at least we had a really short walk that lasted a really long time.	'),
('	MadeforMinaj	','	Wow. RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	khatzurc	','	PLEASE DO EVERYTHING WRONG WITH ANNABELLE :) cinemasins	'),
('	marieee_here	','	The #Drumline2 bull? Im taking my as to sleep lucky I anit pay no money for this like #Annabelle ??	'),
('	num1partyanimal	','	JimCarrey love ya Jim !! Cant wait to see you in #DumbandDumberTo ?? have a great day !!	'),
('	HoIyNickiMinaj	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/8ctVxvFQ0V	'),
('	BINGHAO_	','	Annabelle tonight. ??	'),
('	_princeADM	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/UiTzyl5NcF	'),
('	ESIOTROTCOM	','	sooyoungesio annabelles character will be reserved for you ; u ; will you be joining the games?	'),
('	ThomasAnakin	','	In the middle of #Marvels cinema domination some1 had the nerve to put out a flick called #Nightcrawler with no mutants. #nerdrage	'),
('	LexxxiLynn	','	someone go see ouja or Annabelle with me ????	'),
('	meghanborton	','	annabelle http://t.co/vXvTGbi2M8	'),
('	_JaayMinaj	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” FUCK EVERYONE ?	'),
('	JoshVidana_10	','	Me jonas Pablo and melissa "lets go watch Annabelle?" 	'),
('	Sergio "hey naw Imma be scared once I get home" ?? #pussysergio	','		'),
('	Josh_Wilding	','	Cant find a good time to see THE BABADOOK but crazy excited for NIGHTCRAWLER this Friday.	'),
('	onikazbarb	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” ..................................	'),
('	__OctobersOwn	','	Bitch......... “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	_Emmitt	','	? RT LOOKINFORAMINAJ: “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman. http://t.co/BNQaovBo53	'),
('	ralphbigsal	','	JustPhil4Real: how about Annabelle?	'),
('	FlorenciaTepi	','	annabelle	'),
('	AmyAstley	','	Roy Conli in Sydney #BigHero6 DisneyAnimation http://t.co/vIcqghpPXG	'),
('	thriftqueenxo	','	Apparently I look like Raggedy Ann... I think you mean Annabelle.  ???	'),
('	iCobiRozay	','	"ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman."	'),
('		','		'),
('	BULL FUCKING SHIT. !	','		'),
('	JimmyFineAss	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” yesss	'),
('	alexissavois	','	MegKinc TheFunnyVine brittcutrerr annabelle ???	'),
('	danarchie6	','	wu_tangsam Annabelle	'),
('	basquiiatt	','	nightcrawler will be seen this weekend.	'),
('	OnikasAngel_HB	','	Nobody wants that shit RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	SizzlePod	','	Nightcrawler Film Review - http://t.co/Si6YZ9Hfgw http://t.co/vetsYNNbud	'),
('	LynnaBabe	','	#film Nightcrawler Film Review - http://t.co/9Sg9OTxNnH http://t.co/pvwIGMFbYj	'),
('	KingxxJames	','	Nobody wants it. He can keep it tbh “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	sirmarcuslomboy	','	276. "If shes a sweetheart I maybe might call her. Make her ex-man blue in the face...Nightcrawler."… http://t.co/MjGaUDdfAn	'),
('	AmorMarcie	','	HOLY SHIT. #GoneGirl is CRAZY.	'),
('	LoveThySole	','	Nice RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	MrsLaurenMinaj	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/SBpwzUDlX4	'),
('	tosszolanski	','	GET THE FUCK OUT RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	jauregracie	','	I want an Annabelle doll!!!!! — jabsbsjsjj why http://t.co/w9hBKzQFiA	'),
('	KassiGojcaj	','	some extreme Annabelle shits happening in my room rn	'),
('	nixypls	','	Annabelle ? connor_costa mtrepiccione1 CoolCatMegann ethantbh	'),
('	_MVRKIE	','	Did birdman really? ?	'),
('	FixItJezus	','	Ugh I hate Birdman gap tooth ugly head	'),
('	_Emmitt	','	Birdman always fucking something up	'),
('	SimonHausner	','	It was super fun fantastic art/animation and had a great cameo. Congrats to the Man of Action guys. #BigHero6	'),
('	davidson_jack34	','	Annabelle tomorrow ???	'),
('	HickU_U	','	Foto: fuckyesbeyonce: Beyoncé Jay Z & Jake Gyllenhaal at the ‘Nightcrawler’ Premiere in NYC. (10-27-14) http://t.co/ZbqerBDfkA	'),
('	da_real_kingtae	','	Birdman...bitch I got them birds man	'),
('	HoIyNickiMinaj	','	FUCK YOU BIRDMAN FUCKING WORST RAPPER ALIVE I HOPE HE GETS EBOLA	'),
('	OnMyQueenShit__	','	ComplexMusic: The Rich Gang 2 album will be released on November 24 according to Birdman. What is going on got me havin mixed emotions???	'),
('	philgubert	','	Citizenfour is masterful documentary filmmaking	'),
('	DrawingRoomNYC	','	Edward Snowden Doc Citizenfour Is 2014s Biggest Opening for Non-Fiction http://t.co/eG0ls2lxvv #nonfictionfilm	'),
('	chasemylovex	','	This is bullshit RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman	'),
('	MontaySoWavey	','	Ssssgetit RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	xmeamERICanx	','	#MovieNight #GoneGirl - had to get an Icee and Air Head bites!  Cinemark At The Pike http://t.co/Svy8qcef4G	'),
('	RoadshowFilms	','	markh110 Hi Mark - If you tell us which state youre in wed be happy to find the closest session to you. Thanks :) #JohnWick	'),
('	Anjani_Patel1	','	#TheBestOfMe is hands down one of my favorite movies from NicholasSparks ???	'),
('	JosePonceR	','	Annabelle	'),
('	Paige_Knight_RP	','	ItsSummaXBetch Whos that woman 	'),
('	Annabelle !! ?	','		'),
('	Onikachu	','	goodbyE BIRDMAN5STAR RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	naitiegomez	','	Annabelle ?	'),
('	Parkdara	','	RT ThatPersianGuy: My body is ready. RT OGJOHNNY5: Rich Gang 2 is coming November 24th according to Birdman on Flex show.	'),
('	EazyBreeeeeezy	','	Im guessing domo just saw Annabelle?	'),
('	ChrisMinajs	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” Umm......... http://t.co/3gzjD2kPrT	'),
('	sita_anjali	','	#GoneGirl was rather disturbing and twisted...	'),
('	theangelfuentes	','	Birdman is an excellent film! The story direction cinematography cast everything was flawless. Please go see... http://t.co/x9l1iNko3e	'),
('	nikB__	','	Making Annabelle grease my scalp with hair magic ??	'),
('	Yamiilasosaa	','	Annabelle con Camy y Ana Belen	'),
('	1017Yankee300	','	"Birdman - Type Beat ( Gino Marley/ Fredo Santana/ SD ) [ Prod By YankeeOnDaTrack ]" : http://t.co/Ymo3mjQa8j via YouTube	'),
('	CorieMarrietaM	','	Watching Annabelle — https://t.co/jvT5TNiwqa	'),
('	_Emmitt	','	Oh Birdman....makes me wanna snatch that star off his bald head	'),
('	FLScreenings	','	Free Advance Movie Screening of Nightcrawler (SeeNIGHTCRAWLER) in Winter Park FL via OrlandoWeekly (Contest) - http://t.co/JvWpDrHR2D	'),
('	meganmax2010	','	•There is a lot of magic between you two aint no denying that. & magic makes forgettin hard• #TheBestOfMe http://t.co/nXBnDUSvBy	'),
('	RoadshowFilms	','	FlickChick19 lukebracey Will do! Cant wait :) #TheBestOfMe	'),
('	FIOYB	','	RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman. http://t.co/CjLiziTTd4	'),
('	GeekyGlamourGrl	','	Hi misspyle! Did you read #GoneGirl b4 you got the script? Whatd you think of adaptation? Any other fave reads currently? Thx! #tweetout	'),
('	Gossip_Dawg	','	Ouija spooks N. American box office competition   http://t.co/vQOXRkxG1W	'),
('	  #boxoffice #bradpitt #johnwick	','		'),
('	GetChoLife1	','	Birdman needs to release his shit Feb 30th ...???	'),
('	airis_mcda	','	annabelle with themm =)	'),
('	jennypoo114	','	Annabelle just ripped a really loud fart ??	'),
('	Slay_4_Nicki	','	This y Nicki shouldnt have said SHIT RT "softnoir: “Slay_4_Nicki: What birdman do?” http://t.co/9Qa1tOY77k" http://t.co/UQoTkMZ0Hc	'),
('	Tyrique_Nicki	','	ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman. http://t.co/u8ClazCn3g	'),
('	Arturo_Nav4s	','	Annabelle Dig Sub - 27 octubre  http://t.co/p532eFBBA4	'),
('	L_Fields11	','	AlexandraaRuiz NO ONE IS EVER EGYPTIAN!!!! Be the Annabelle doll	'),
('	YeLATimes	','	Avast!  Ouija scares up $20 million in opening weekend; John Wick  http://t.co/1taKCrBvTQ	'),
('	  #boxoffice #johnwick	','		'),
('	RBooGie3	','	Lmao right “QuanJ_5: That Rich Gang mixtape got Birdman thinkin he can hop on tracks again ?”	'),
('	ComicOnBox	','	MAA Marvel Nightcrawler Handmade Upcycled Cigar Box #cigars #comiccon #marvelcomics #comics http://t.co/bDcxbYTGDR	'),
('	Canada33_Nelson	','	Nice to relive my childhood while watching #TeenageMutantNinjaTurtles although I dont remember them being such heavy steroids users...	'),
('	_JaayMinaj	','	FUCK BIRDMAN  IGGY  EMENIM  BEYONCE  AND WHO EVER ELSE RELEASING THEY SHIT	'),
('	unbotheredx	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” I hate YM.	'),
('	PeronLeonardo	','	Mc + cine.  #Annabelle	'),
('	ShanenMckenzy	','	At #JohnWick. Gals vs Guys #IMAX tonight:? 20 ?50 #HelloLadies 	'),
('	#meatmarket #itsgettingdark #icantcountanymore #testosterama	','		'),
('	MarajDreamz	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/kQr1KiRxk2	'),
('	VMDoggi_CEO	','	Ex Young Money Artist Lil Chuckee Filed Molestation Charges Against Birdman http://t.co/UYKUCUmpaQ	'),
('	MarajVibes	','	.... RT “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	megasoft012	','	Annabelle (2014-10-03) subtitles - Download subtitles for Annabelle (2014-10-03). http://t.co/qvho2ZArDl	'),
('	nics_cakes	','	Or never "GetChoLife1: Birdman needs to release his shit Feb 30th ...???”	'),
('	kenny_veloz	','	"Ace_IOD: Chillin w the homie kidglorymusic at Bowlmor Lanes Lit asf #IOD #NightCrawler" lmao	'),
('	NicsHeartBeat	','	THEmale_madonna KingKillerBee . Im so fucking passed ! Fuck Birdman!	'),
('	edwinsallan	','	Annabelle Rama to daughter Ruffa Gutierrez: ‘Find a stable man!’ | Entertainment News – http://t.co/BRcVsSmSgj http://t.co/szUKvGZ02P	'),
('	MrStrongvoice	','	Im reading this book because I heard it is a good book.  #reading #book #GoneGirl #loveit #wwwyki… http://t.co/I76EMSPjNG	'),
('	Connor_Fleniken	','	Studley_75 way to steal Annabelles idea http://t.co/NxopmDXY3t	'),
('	JShmoneyboi	','	Emma_Vasquez_ so you wanna go see Annabelle ?	'),
('	50ShadesOfPetty	','	"ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman." http://t.co/txQonggwt1	'),
('	D_daFOOL	','	I be jammin until I hear birdman on a song	'),
('	SHAQBLAC	','	"LA_isOfficial: How cool is it to be in a relationship with your bestfriend? Thats how it should be" *birdman hand rub*	'),
('	CharlieBurburyy	','	Cant wait to see intersteller Christopher Nolan hasnt made a bad film in his life	'),
('	JeSuisJai	','	When Birdman hops on a verse:  http://t.co/4PlFm75Zal”	'),
('	ConnerHabib	','	Whiplash and Birdman are 2014s two best movies to walk out of.	'),
('	highkeygoon	','	RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman. http://t.co/TfwX73BXeo	'),
('	LlIsayganda	','	Ruffa Gutierrez And Annabelle Rama In Twitter War | PINOYSTOP http://t.co/HOVteVgans via sharethis	'),
('	chloe_z12	','	ME AND MY BRITHERS R WATCHING ANNABELLE AND WE R SCARED IT WAS A METAPHOR OK paige9282 TheCamRosales	'),
('	iimanuell_	','	Annabelle Closing by Joseph Bishara — https://t.co/4oMvp1FWGl	'),
('	Mystical_Gift	','	_FallenBeauty *Annabelle almost chuckled down the phone line.* The petty rich boy? Besides stuff I see on television all I know is that -	'),
('	Retro_O	','	Watching Annabelle	'),
('	ZAIREMINAJ	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/hlktdUcK2Q	'),
('	euphoriccells	','	Birdman suck ass	'),
('	CheMill34	','	So has anyone read Gone Girl? Is it good bad? #GoneGirl	'),
('	Bhead_	','	When ur mom hits u up and says she cooked too much food *birdman hand rub?*	'),
('	TehLATimez	','	Nightcrawler shows how the news worm has turned -  If it bleeds it leads in the... http://t.co/6XtHRhdOd3	'),
('	 #JakeGyllenhaal #LosAngeles	','		'),
('	ChristinaSoliss	','	L_Fields11 AlexandraaRuiz yea be annabelle ?	'),
('	iRawq	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/3rq4fDaFCa	'),
('	MarajDreamz	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/rO5tKfw2Cm	'),
('	Parkour_Lewis	','	Subeylove *Follows birdman handrubs*	'),
('	hockings99	','	ashleyy_watkins annabelle	'),
('	ShvwnOMO	','	RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	LYFEafterDEF	','	Master P better than Birdman facts of life	'),
('	nickbarrientos_	','	Im locked out of my house gotta watch out for Annabelle  :(	'),
('	FM0C_Los	','	I want to see Nightcrawler Fury & Dumb & Dumber To.	'),
('	matthcute	','	call joey he always tries to scare me so pretend youre that creepy doll Annabelle and accidentally say dont look in your closet 2036952436	'),
('	ObeyKatie	','	Annabelle scaring tf outta me son	'),
('	TheTTT333	','	ANTxMARAJ yes for TP...Rich Gang is Rich Homie Thugger and Birdman and its coming in December as of now	'),
('	bibitsuan	','	Regal Cinema movie house :) more or less 15 cinemas inside.. #regalcinema #reg #draculauntold… http://t.co/sfzhi08Y1o	'),
('	Kat_movies	','	[CouchPotato] Found 4 releases for "Annabelle" before ETA. Select and download via the dashboard. naesstrom	'),
('	FvcKingZach	','	MarkoftheGODS I heard Birdman is releasing an album that day but the Black Friday sales wouldve sky rocketed if she kept that day ?	'),
('	shampainxcx	','	wait so nicki pushed back the pinkprint just because birdman wanted to release his fuck ass album that day?	'),
('	talkdatrih	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/0IULIwk5S4	'),
('	Gossip_Dawg	','	Ouija spooks N America box office competition #boxoffice #BradPitt #JohnWick #KeanuReeves #NorthAmerica #Ouijaboard http://t.co/X5IObiv0R5	'),
('	JavianMinaj	','	Gurl Birdman is trying the Wrong Stanbase rn NICKIMINAJ	'),
('	iconicslave	','	is this why? fuck that. RT “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	euphoriccells	','	“LYFEafterDEF: Master P better than Birdman facts of life”facts	'),
('	pachelee	','	So birdman said Richgang album is nov 25 ?	'),
('	Boom_likean808	','	So Birdman pushed Nicki album back for Rich Gang album. Ok.	'),
('	jessups	','	ODEONCinemas Looking forward to this I think RDJ is a great actor. would like to win some movie goodies too #TheJudge	'),
('	ncampusano	','	Lesson learned after reading #GoneGirl ... Theres never a happy ending	'),
('	flossynigga	','	It was a 1? RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	Trent_Warner	','	#Virtue#Character Review: Birdman or (The Unexpected Virtue of Ignorance): Co-writer/d... http://t.co/Xmu3dIrv9L #CharacterLeader.com	'),
('	Aissablabla	','	“BeyonceLite: Beyoncé Jay Z & Jake Gyllenhaal at the Nightcrawler Premiere in NYC http://t.co/e0KR3hubsz”J always the 3rd wheel ??	'),
('	dearnickiminajx	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/59AA2xuvIg	'),
('	____ness	','	#Inktober day 27 heres Beymax! #BigHero6 screened early at the savfilmfest and it was AWESOME! DisneyAnimation http://t.co/VBI91jVPDg	'),
('	nerdography	','	Amy Dunne is my role model in relationship from now on. #gonegirl http://t.co/QBAv5Bn2CW	'),
('	scottysqueen	','	Went to see #TheBookOfLife Great movie. I must say.... #TodayWasAGoodDay	'),
('	jakexhathaway	','	Itd be sick to go see Annabelle or Ouija with a hawt bish tomorrow	'),
('	ThatStalkerAnna	','	itskpierce hello Im Annabelle call me Anna pls	'),
('	DoctorBombshell	','	Holy mother of dark and twisted what the fuck did I just pay money to see. #GoneGirl	'),
('	jauregracie	','	idk I just want one dont you wanna met the Annabelle doll best friend — hahahavwvebb noooo http://t.co/5C6saaaXc9	'),
('	Michassiopeia	','	wow this book is almost as thick as The Fault in Our Stars	'),
('		','		'),
('	but Im still on the 62nd page #TheMazeRunner	','		'),
('	hellofrmSG	','	grubbypea ANNABELLE	'),
('	emilyyssmith	','	I wanna see Ouija again and I wanna see Annabelle but there is no way in hell Im going alone ?	'),
('	So_Utweet_Huh	','	Watchin Annabelle wit my lil creeps	'),
('	hans996m	','	After watching annabelle. Ask me if i can go toilet at night?	'),
('	Bribabii33	','	All these bitching ass old men. I will defeat them all. *Birdman Hand Rub* http://t.co/33nDOAbbz0	'),
('	MinajOrNahh	','	Hmm... RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	PinkFreak4L	','	? “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	jaspers47	','	83/100 Birdman. 5 out of 5. #100moviesin2014	'),
('	karooles_	','	Me: Annabelle	'),
('	You: Barbie"	','		'),
('	viveksshharma	','	KayDMusiQ Navjosh help to keep wayne hot and relevant .. Nicki fans will be forced to buy the wayne CD and help sales + birdman LMAO	'),
('	JakeSchneider19	','	Gotta see Interstellar & Nightcrawler ?	'),
('	pachelee	','	So birdman said nov 24 for the Richgang album ?? instead	'),
('	Dino_Brown	','	RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	Mayumi_juh	','	Me: Annabelle	'),
('	You: Barbie 	','		'),
('	Kk	','		'),
('	ChristianOVO	','	Hold up... RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	MaariDiaz23	','	Cine Annabelle with LuMartinez08 #QueMieeeeeeedo	'),
('	_emmamyles	','	You guys #nightcrawler was the TITS. Such a fun and super messed up ride. SeeNIGHTCRAWLER	'),
('	favgirlcrush	','	Best movie ive seen in 2014. #birdman #michaelkeaton #theenexpectedvirtueofignorance #al... http://t.co/2haHKiOrSi http://t.co/8x1hD3LBb2	'),
('	OVOalexx	','	“BeyonceLite: Beyoncé Jay Z & Jake Gyllenhaal at the Nightcrawler Premiere in NYC http://t.co/MCBFRPGCsz” Jake?	'),
('	KennethWayne_	','	"ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman." We want C5!!	'),
('	ButIsItNew	','	Birdman Announces Rich Gang 2 will Drop November 24th - http://t.co/DWEjgenFmj BIRDMAN5STAR	'),
('	_tiffanyloveee	','	turn it!  RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	CoachRippa3000	','	Fina go catch a movie tho ? #Annabelle	'),
('	nkd_123	','	KayyOhh_x3 *birdman hand rub*	'),
('	valopz	','	Nightcrawler - Red Band Trailer YEAHH! ? http://t.co/FHquRyvBE8	'),
('	Lenaa_Bby	','	Watching Annabelle right now ???	'),
('	IInventedTwag	','	Birdman Announces Rich Gang 2 will Drop November 24th - http://t.co/YQho6aYrgt	'),
('	ButIsItNew	','	Birdman Announces Rich Gang 2 will Drop November 24th - http://t.co/DWEjgenFmj	'),
('	ILeaK_it	','	Birdman Announces Rich Gang 2 will Drop November 24th - http://t.co/czjIOHTkNT	'),
('	iStan4_ONIKA	','	Im annoyed ??? RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	m4ttkellz	','	Birdmans mentions right now :(((	'),
('	nashhloml	','	TheMattEspinosa Im watching Annabelle and Im scared but theres like no one in this theater so I get to scream as loud as I want	'),
('	HuginsPL	','	#Birdman (4/5) I really enjoyed it.  Had some real stellar stand out moments.  Didnt love it but plan to read up on it a lot!	'),
('	_FallenBeauty	','	Mystical_Gift Annabelle Matthewsthat is your namecorrect? {The woman on the rifle allowed her eyes to narrowher attitude wasnt helping<	'),
('	XxjewelztoolzxX	','	I want that annabelle doll so badly ??? http://t.co/q5Uc89L3PC	'),
('	Michassiopeia	','	Im a fast reader maybe Im becoming a slow one lol	'),
('		','		'),
('	...or maybe Its just the font and every page is really packed #TheMazeRunner	','		'),
('	AbigailPapousek	','	Finished my book! So good cant wait to see the movie! I recommend it to anyone! #GoneGirl	'),
('	Cuntassel	','	Whoever said Annabelle was scary straight tf lied. Corny ass movie ?	'),
('	MikeNike_23	','	Young_Simbaaa Annabelle a hoe tbh	'),
('	QuxxnsMinvj	','	Nah I refuse....I fucking refuse RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	_conallkeenan	','	Annabelle is such a bad movie	'),
('	drchriswolfman	','	Movies I have to see in the next week or so: Fury Birdman St Vincent (Bill Murray!) Men Women & Children John Wick	'),
('	Mattlewinski16	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/acp2C9eMB8	'),
('	momentumartist	','	Should I watch annabelle or equaliser on Thursday ?	'),
('	_Emmitt	','	DMAIJTHERAPPER Birdman	'),
('	BeyonceLejen	','	The Carters at The "Nightcrawler" Premier with Jake Gyllenhaal. http://t.co/lc3aoqAKNG	'),
('	DeejRoth2	','	Yall remember Birdman? This is him now. Feel old yet? http://t.co/KDXYEwdxoj	'),
('	mrsamagax	','	.Felicity jones & Eddie redmayne both so good in #TheTheoryOfEverything FocusFeatures does it again	'),
('	MinajOrNahh	','	sugarbarbz HarajukuBrandon IloveOnikaT birdman releasing rich gang album on 24th. Thats why TPP is pushed back.	'),
('	_iBeezWithOnika	','	Birdman aint shit!	'),
('	carusso_lol	','	someone pls talk to me while Im watching Annabelle.	'),
('	Comic_Break	','	Photoset: bear1na: Batman Captain America Wolverine Nightcrawler Thanos and Magneto by Brandon... http://t.co/2QhQDQAaRv	'),
('	GloriaaDeluss	','	“momentumartist: Should I watch annabelle or equaliser on Thursday ?” The Equaliser	'),
('	stephwuk	','	Uuyat I think its called Nightcrawler	'),
('	Shemz_TM	','	Man fuck birdman	'),
('	KensReloaded	','	Wut? RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	Naees__	','	“_iBeezWithOnika: Birdman aint shit!”	'),
('	_Jace_Carter	','	I wanna see nightcrawler so bad on Friday but no one makes plans with me	'),
('	caritoovando12	','	iHunterHerring Annabelle ?	'),
('	PreettyMonroee	','	Annabelle was hella scary	'),
('	vaiprocarolio	','	Annabelle	'),
('	Slay_4_Nicki	','	But the thing is.. NOBODY give a shit about Birdman or Iggy...so them dropping their albums on Nickis date has me unbothered.	'),
('	CPrice_504	','	Next thing I see she has literally stuck her entire hand in the yogurt and hitting the Birdman Handrub with it ?	'),
('	HarajukuBrandon	','	MinajOrNahh sugarbarbz IloveOnikaT did Birdman truly confirm this?	'),
('	AmericanAssh0le	','	cocainemodel GOOD! I wasnt scared at Annabelle so Ive been holding off seeing this	'),
('	breanna_kim1	','	Annabelle and Ouija are some shitty ass movies	'),
('	BlueberryCath	','	Nw: Annabelle	'),
('	iconicslave	','	can we stone Birdman?	'),
('	gokulsan	','	#TheJudge (English): is an excellent film and a must watch. An estranged lawyer (Robert Downey Jr) meets his... http://t.co/PaRPOdN8Kd	'),
('	ria_xox	','	momentumartist Annabelle is dead?	'),
('	StephGambini	','	Movie time! Im watching #XmenDaysOfFuturePast. Join the conversation on #tvtag http://t.co/zzZsBBIfDv	'),
('	connormyw	','	taylorcolleging absolutely. Next stop: birdman	'),
('	MrsLaurenMinaj	','	Fuck Birdman!! http://t.co/sj51A357ws	'),
('	ctvwa	','	Post Edited: Real Annabelle story shared by Lorraine Warren at Milfords Lauralton Hall - New Haven Register http://t.co/SLbgoHfGpk	'),
('	RDavidOnTheWire	','	Just clearing those Oscar slots for American Sniper & Birdman. RT“DanielVMcCoy: Interstellar has a 72% on Rotten Tomatoes. Fix it Jesus”	'),
('	Klinethefinest	','	Im thinking Im back! #JohnWick FebbsBurger	'),
('	k_ashanti	','	and Birdman can go to hell	'),
('	CobesMom__	','	Is it true about BirdMan molesting Li Chucky. ?	'),
('	iKeyDay	','	“CAGRustyRyan: This Nightcrawler film might get me to the movies.” I second that brah	'),
('	ctvwa	','	Post Edited: Annabelle True Story: 9 Freaky Facts About The Real Doll Haunting Ahead Of ... - International http://t.co/5H0ZNEdS1t	'),
('	dollssharaff	','	mariamnazim ur header creepier than Annabelle tf	'),
('	zainaujayli	','	two hours of extras? You really do love us wesball #TheMazeRunner #Ineedthatdisc	'),
('	CocoPuffs_1994	','	"BeyonceLite: Beyoncé Jay Z & Jake Gyllenhaal at the Nightcrawler Premiere in NYC http://t.co/DIJwd5nufO" jay shouldve wore slacks	'),
('	smilesofheroes	','	_DanialMalik DANIAAL YOU WERE WATCHING ANNABELLE OR NOT?? ?	'),
('	AyodeleMinaj	','	How many albums can come out this day ? RT “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	stfuaiyanna	','	“dearnickiminajx: “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/DvSYk8cR8A”??	'),
('	syafanamiraa	','	Telat banget ya kitaaa?? ? Annabelle (with Audry) — https://t.co/fhLFy35E4p	'),
('	billynomatess_x	','	momentumartist annabelle is crap	'),
('	HuginsPL	','	Though to be honest I think I enjoyed #Birdman far more as a technical challenge for Emmanuel Lubezki than I did as a story or narrative.	'),
('	itsSheedSavage	','	Birdman ruins every song on god	'),
('	Lyndsey212	','	pankeypancakes KelseySchmucker annabelle is really good?	'),
('	BrandonBlair2	','	***Watching Annabelle	'),
('		','		'),
('	Nigga if Father aint safe in the church whos safe?	','		'),
('	BrianFerentz	','	KirkFuhrentz hey can I go to nightcrawler Friday night	'),
('	ImJadeGabiola	','	Annabelle (2014) http://t.co/MexiUhr3j9 via sharethis	'),
('	JayBMinaj	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/6uL6AkLzCa	'),
('	FebbsBurger	','	Klinethefinest its what you did its who you did it to #JohnWick	'),
('	BaldHead_BREE	','	Annabelle better be good.	'),
('	MovieCriticFeed	','	#Movie Reviews - Movie review: Annabelle - Virginia Tech Collegiate Times http://t.co/PInnO1s4Kv	'),
('	NonStopPop	','	Not thrilled that our lone local press screening for "Birdman" is at 2 PM tomorrow. Oh well Ill see it eventually Im sure.	'),
('	rihennafenty	','	"ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman."	'),
('		','		'),
('	ITS TIME FOR HER TO PACK UP	','		'),
('	JulesArk	','	eshynes Theres always someone whos looking to poop the party... *shakes head* http://t.co/NPZaNWKlcW	'),
('	Dare_Mrks	','	I really wanna see the movie Annabelle or whatever its called hah	'),
('	InukiGreYHounD	','	My new fan-art ))) #BigHero6 http://t.co/zPrPqURbZG	'),
('	AlyssaaaaJ	','	Been trying to watch Annabelle for days now .. Still havent got to watch it ??	'),
('	Taquillaxoxo	','	Watching annabelle with the 3rd floor hall girls. #dormlife	'),
('	x_NicSantiaga	','	is this a fucking joke? > RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.	'),
('	DollEduardo	','	My girl Iggy in Annabelle ? http://t.co/Truf9JHMU2	'),
('	ThxCashew	','	“TheMattEspinosa: Ok so so far we got Burnie Larry bagels and pizza. Any others”	'),
('	ANNABELLE	','		'),
('	NiplV	','	birdman and lil wayne ass niggas	'),
('	MuFaSaMiCoNnOr	','	Not buyin unless they sell The Pink Print w/ RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman	'),
('	ScreechDiddy	','	woodyLFC09 I loved Birdman so yes	'),
('	QuintaNadiars	','	Watching this movie in the class? ? Annabelle — https://t.co/s77QddSsG4	'),
('	DanielVMcCoy	','	RTInheritVice NO “RDavidOnTheWire: Just clearing those Oscar slots for American Sniper & Birdman. "DanielVMcCoy: Interstellar has a 72%””	'),
('	NadixNika	','	adamrickards Birdmans album probably. :((((	'),
('	M_FB1	','	Listen. Whoever told me Annabelle wasnt scary is a liar. A goddamn liar.	'),
('	dudemau5	','	Gonna see #Birdman again this week. Ill probably have seen the #film 10 times before it finishes the theater run.	'),
('	grashu123	','	“BeyonceLite: Beyoncé Jay Z & Jake Gyllenhaal at the Nightcrawler Premiere in NYC http://t.co/fnLVPUruxn” *crops Jay Z out of the pic*	'),
('	whoopDERitis	','	Lets see how much more f***ed up the book is... #gonegirl http://t.co/fAssvGLTow	'),
('	AyooArie	','	This flop shit... RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	Pxs3	','	?  RT D_daFOOL: I be jammin until I hear birdman on a song	'),
('	KeyshiaMay	','	“momentumartist: Should I watch annabelle or equaliser on Thursday ?”Annie	'),
('	ShamelessRager	','	Someone come watch Annabelle with meeeeee.	'),
('	NYRPrincess	','	Leekowalski did you happen to see Annabelle?	'),
('	jeangenierose95	','	Im going to check out #GoneGirl and #Ouija to see if theyre any good.	'),
('	zaynpasstheweed	','	I just watched Annabelle	'),
('	kurniasaridesi	','	? ? Annabelle — https://t.co/rmaurIeBz7	'),
('	DewiWulansakira	','	Neshabelle nonton Annabelle??? (with Risky and Nesha at SMA Kesatrian 2 Semarang) [pic] — https://t.co/5IviwBGfwS	'),
('	sunnyotakuu	','	Not again... #movies #myself #johnwick #ihavetheweirdestluck http://t.co/ue4kcInXkc	'),
('	TedKottler	','	VIDEO: Snowden Pays Tribute to History in "CITIZENFOUR" Introduction  --  https://t.co/ICHXBgmZxd via aclu	'),
('	dipaaakkk	','	Watching Annabelle (with Indah Salma and 6 others) — https://t.co/bXyZnJ8Bxh	'),
('	Jada_hart_	','	why is my mother watching annabelle in the night ?	'),
('	JPmovieblogger	','	#BirdmanMovie a hallucinogenic riff on mid-life crisis alternately hilarious and dazzling. My review: http://t.co/ptV6RceFov	'),
('	YoAmoOnika	','	??? “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	JennM14	','	So weird that about a year & a half ago we saw a scene from #birdman being filmed in NYC. And now its a big deal! Anxious to see it!	'),
('	Ms_JasmineRenee	','	I heard it is RT BaldHead_BREE: Annabelle better be good.	'),
('	ElezovicT	','	I dont think anyone understands (or cares) how excited I am to be seeing #TheBestOfMe tomorrow night ?	'),
('	joako5a	','	annabelle*	'),
('	ovo_kierra	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” Why :(((	'),
('	moankidrauhl	','	so like I seen Ouija 2 days ago it was pretty scary but ANNABELLE was better	'),
('	onlykath142308	','	Nw: annabelle	'),
('		','		'),
('	#GoodMorning :)	','		'),
('	#MovieMarathon ;) http://t.co/5KK4tuSwJL	','		'),
('	aklimuuur_x	','	And youve just watched annabelle	'),
('	Isaac_J1	','	Naaaaaaaaaaaaaaaaah. Annabelle is a fucked up film.	'),
('	hamsandals	','	Im so excited for Nightcrawler	'),
('	CristinaBlack	','	The best part of Birdman is the confrontation between artist and critic. They both think their own work is worthy and the others isnt.	'),
('	Lea_Vrk	','	alexrhinorouss annabelle ??	'),
('	Chad_Minaj	','	Something Abt Birdman Sayin His Album is Releasing on Nov. 24th. RT “AyodeleMinaj: Why is everyone saying TPP is pushed back?”	'),
('	CECEVELLI	','	i feel like Birdman just does things that cost money because he has money.	'),
('	theclassyguy__	','	I havent seen Annabelle or ouija yet ?	'),
('	GlovezOfficial	','	Thought the #Equalizer was bad ass till I saw #JohnWick that movie was bad ass times 100!	'),
('	jadamaraj_	','	"ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman." http://t.co/tmlg0DsFxt	'),
('	TreHunnid	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” http://t.co/CYVF7LSF1A	'),
('	cherrylipshoran	','	HIIII IM WATCHING ANNABELLE ALONE RN I	'),
('	emilyyybeee	','	we were supposed to watch annabelle & ouija ):	'),
('	onikazbarb	','	Birdman is deadass finna catch a fade fam wtf	'),
('	moankidrauhl	','	Why did my phone capitalize Annabelle lol ?	'),
('	BaldHead_BREE	','	? ok good RT Ms_JasmineRenee: I heard it is RT BaldHead_BREE: Annabelle better be good.	'),
('	lizatweet	','	"This may undermine my non-threatening huggable design." #BigHero6	'),
('	CashsSecret	','	TheMattEspinosa Halloween or Annabelle or Ouija board or anything scary af	'),
('	ziggystarslut	','	Birdman is an ugly bitch. He could burn in a fire and no one would show interest.	'),
('	KaroDogfood	','	#Movies Steve Carell and Channing Tatum Descend into Darkness for ‘Foxcatcher’-Hot News - http://t.co/JF4X3WKRlf	'),
('	ashhleyv	','	Can Not Wait. #birdman https://t.co/38PIHkT0Nm	'),
('	ValussiAgustinn	','	ANNABELLE !!	'),
('	enostarr	','	will watch Birdman for Michael Keaton	'),
('	lizzyhubbard	','	Sequel to Annabelle"Lizzy" coming to theaters near you http://t.co/a32i85wqhq	'),
('	fabiaguilafc	','	#idied!! #imdone!! Well there is pic of Lil Wayne kissing Birdman!! Tupac 4ever!! #fucklilwendy http://t.co/XkzF53Bk4D	'),
('	maxduchenns	','	Set de fotos: disneysbighero6-bh6: A sneak peek of the #BigHero6 Bot Fight App that will be available to... http://t.co/Hzck49BhdG	'),
('	boltzwithaZ	','	Peyton may not realize this yet but after I make him happy with sonic for dinner on Wednesday hes taking me to see Annabelle ??	'),
('	MaturePix	','	Annabelle Lee #milf pictures http://t.co/H7aBYrAYmT Beautiful and fit hairy beauty Annabelle Lee teases in her dress showing her panties. S	'),
('	tychae13	','	really want to see Annabelle	'),
('	CorySlump	','	#Citizenfour was awesome.	'),
('	theotherkiki	','	watching annabelle... its kinda weak lowkey	'),
('	u_aint_Real02	','	“JolieBomb: “iAmBrooklyn_1: ??? RT JolieBomb: I hate being home alone at night I be scared”???” u home alone hit birdman hand rub??	'),
('	audryretno	','	Watching Annabelle (with Syafa) — https://t.co/WAmXmYyRR3	'),
('	jennxo393	','	Watch Annabelle Leanne said. It would be fun Leanne said. FUCK YOU lebitch14	'),
('	_haleylynn14	','	if youre going to try to get me to go see Annabelle or Ouija just stop. its not happening	'),
('	_BunzMinaj	','	Like wtf... “ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.”	'),
('	VeryAw	','	INTERVIEW: #NIGHTCRAWLER Writer-Director #DanGilroy Talks Inspiration & Corporate Ethics http://t.co/1OrvEiJnXB	'),
('	Ashley_Anthony4	','	GabbyCalametti4 have you seen Annabelle yet ?	'),
('	makellathompson	','	Im honestly terrified from watching the conjuring and Riley sent me a picture of Annabelle and said good night.... #fuckuuuu ?	'),
('	RomanZalinski	','	Why the barbz pressdt that birdman releasing on nov 24 because that means nicki is most likely pushing hers back id rather have tpp december	'),
('	farahqutub	','	My go to steps if you wanna be annabelle for Halloween http://t.co/ulQ3XQIcRU	'),
('	AnikaRahman12	','	I think Blank Space is a great song to go with Gone Girl. My two favorite things together #TS1989 #GoneGirl	'),
('	MeJill	','	Jake looks like a wax figure o_o RT BeyonceLite: Beyoncé Jay Z & Jake Gyllenhaal at the Nightcrawler Premiere http://t.co/SbOmKSyFXb	'),
('	jacknochill	','	“BeyonceLite: Beyoncé Jay Z & Jake Gyllenhaal at the Nightcrawler Premiere in NYC http://t.co/pGJh9yyR8q” SHES PREGNANT U CAN SO TELL	'),
('	owenhh01	','	Nightcrawler looks way too good	'),
('	OVOLyricz	','	No one wanted the first one tbh. "ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman."	'),
('	racheLock10	','	finally saw #GuardiansOfTheGalaxy and IT WAS AWESOME!!!!!! cant wait to see it again on wednesday!!!!!! #IamGROOT	'),
('	Lulamaybelle	','	INTERVIEW: #NIGHTCRAWLER Writer-Director #DanGilroy Talks Inspiration & Corporate Ethics http://t.co/OMokHMLXJs	'),
('	Shesbadnewsz	','	Watching Annabelle	'),
('	SlipShotPerfect	','	Wanted to rewatch Annabelle BUT NO EARPIECE TODAY FAK	'),
('	lillianhallett	','	I wanna see Nightcrawler SOO bad #jakeisbae	'),
('	Emaciel80	','	Annabelle? #WheresBae http://t.co/Pby44ca9Fl	'),
('	SteeVee_D	','	Isnt #BeforeIGoToSleep just a creepy remake of 50 First Dates?	'),
('	courtneyw123	','	Annabelle.. Have you seen the baby? http://t.co/qQLT5jUqRm	'),
('	DylanHalaska	','	Freaking out watching ghost adventures doll island thing because I cant sleep and Im suppose to see Annabelle? ?	'),
('	Road2Oscars	','	I think Ive narrowed tonites poss viewing to btwn #Birdman and #CitizenFour.	'),
('	Time willing!	','		'),
('	BrandonEngg	','	Nightcrawler looks sick gonna see that in theatres	'),
('	_Dillpicklez	','	“MostxDope: UL homecoming this weekend..? *rubs hands like birdman*”http://t.co/agxzIIgcta	'),
('	aimbautistaaaa	','	JedxJose03 jmbRonquillo i want to watch annabelle	'),
('	RobbyBear_	','	I must admit Annabelle was pretty scary	'),
('	mrsjotape	','	"BeyonceLite: Beyoncé Jay Z & Jake Gyllenhaal at Nightcrawler Premiere in NYC http://t.co/uv3h2B4qdR" MUDOU A PERUCAAA!!!! LINDAA MEU BB	'),
('	ovokgwxo	','	So was Nickis album was pushed back for Birdmans album?...??	'),
('	theDXT	','	Going to see #JohnWick tonight	'),
('	ProducerThought	','	Int’l Box Office FINAL: ‘Happy New Year’ Uncorks Record Bollywood Bow; ‘Annabelle’ Still A Doll With $26.2M; ‘Lucy’ Outmuscles ‘Hercules’...	'),
('	AnnabelleMarieV	','	"Annabelle" and "Lovell" are pretty much two of the least intimidating words ever	'),
('	BostonJobs3	','	#Job #Boston Business Systems Analyst: MA-Boston TheJudge Group is seeking a Senior Business Systems Analyst ... http://t.co/9I2c1PXo2e	'),
('	JobsinBoston_	','	#Boston #Job Business Systems Analyst: MA-Boston TheJudge Group is seeking a Senior Business Systems Analyst ... http://t.co/2avX57EkXy	'),
('	larry411	','	#birdman screening ( Cobb Downtown 16 Theatre in Palm Beach Gardens FL) https://t.co/P645qiP6ZJ	'),
('	HIMANSHU	','	So proud of my brother rizmc. Nightcrawler was awesome! Highly recommended!	'),
('	hurrrle	','	I want to see Nightcrawler	'),
('	shannonxtheresa	','	Wanna go watch a good movie (aka Annabelle) at the AMC in Braintree cause that theatre is sick as fuck	'),
('	khunmeenam01	','	Nightcrawler ??? New Film Trailers - https://t.co/Db348XbDBK	'),
('	NewestOnNetflix	','	If You Cant Go See Birdman Watch Biutiful on Netflix Tonight - Gizmodo - http://t.co/qPODvE9Pa0 #newflix #vod #news #tech #tv #television	'),
('	IAMAGAME1	','	JustnChiefer314 Birdman handrub	'),
('	TallestofemAll	','	Annabelle RT Lokecaiga: Caption https://t.co/rw6WYFle4u	'),
('	MinajMeDemi	','	Birdmans gonna flop....can this nigga move so the queen can slay bishes	'),
('	JohnnyRapp	','	Really wanna go see Ouija and Annabelle	'),
('	TheBeyHiveTeam	','	Bey and Jay at the "Nightcrawler" NYC premiere: http://t.co/s1OiQi7zI6	'),
('	angelicastiffy	','	SOMEONE JUST TRIED TO BUZZ INTO MY APARTMENT WHILE IM WATCHING ANNABELLE IM FUCKING CRYING KATIE AND I ARE ON THE FLOOR CLENCHING EACH OTHER	'),
('	OnikasAngel_HB	','	Cause birdman is dropping Richland album instead RT ChanelKnowsBest: The Pink Print got pushed back? WOW. #Mad	'),
('	BostonJobs__	','	#Boston #Job Business Systems Analyst: MA-Boston TheJudge Group is seeking a Senior Business Systems Analyst ... http://t.co/102lPL8Sno	'),
('	shadscameal	','	Chad_Minaj AyodeleMinaj birdman and his irrelevant ass ugh	'),
('	jessielynn_Xoxo	','	Gonna cry watching Annabelle ?	'),
('	NatCrockett15	','	Well I wont be sleep for about a week. ?? #annabelle	'),
('	StarsThaName	','	Check out Annabelle moviefone	'),
('	http://t.co/OLsDSOUATU	','		'),
('	jamiemyass	','	Who the fuck is birdman	'),
('	Road2Oscars	','	I still wanna see #GoneGirl again but the films are piling up. #Oscars	'),
('	Hellen_sud	','	Family ? Boyfriend ? Friend -  Cine ; AnnaBelle  Habibs - tudo de BBOM ? http://t.co/EFe5sNZTLD	'),
('	virayuliR	','	Watching Annabelle (with Hilda Acen and 3 others) — https://t.co/uLWvdi94M8	'),
('	ashleyshoate	','	“MediaGoddess313: 13. Last movie you saw?”	'),
('		','		'),
('	Annabelle	','		'),
('	CauilanClarette	','	Annabelle ??	'),
('	meggie_burda07	','	I want too see Annabelle again.	'),
('	CountDmitri	','	What is your favorite year of your life? — "The year I met Annabelle and the three subsequent years later. I th... http://t.co/hvEWjABOQm	'),
('	Salsaaperbatas	','	Se RT an ? Annabelle (with Alya Nafila and 9 others) — https://t.co/R3JLjbw3nH	'),
('	ChevilEngineer	','	DW: Annabelle. Not that satisfide with this horror movie. But its good. :)	'),
('	Carlos_Damian98	','	Fist Iggy now Birdman want to release their shitty flop music the same day as TPP?	'),
('	UndefinedKelz	','	Birdman took Nicki album release date. What fans do this nigga have? He better put TPP release date back. http://t.co/lGT1to72Ca	'),
('	BurrisAmanda	','	“JohnnyRapp: Really wanna go see Ouija and Annabelle” okay you can take me instead of connor_horton7 bc hes a ?	'),
('	TanyaH666	','	Baymax pumpkin! #Baymax #bighero6 #bigthunderranchjamboree #bigthunderranch #halloweentime  Big… http://t.co/XJ7CkkmDPq	'),
('	ckatt2	','	Whats the movie nightcrawler even about?	'),
('	jadamaraj_	','	"ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman." http://t.co/bT4il5lq3o	'),
('	marvel_toys	','	The #hottest offers on Marvel Nightcrawler  #MarvelNightcrawler #Marvel #Nightcrawler # Compare prices http://t.co/JQoPdYKvHl	'),
('	LegitTonyTone	','	Wow just wow #GoneGirl	'),
('	carusso_lol	','	i dont fuck with Annabelle.	'),
('	sbg_famous	','	Ltiny_  whats scarier Annabelle or ouija board	'),
('	ZGalifianakNews	','	NYFF52 Birdman Press Conference http://t.co/GIO5UvKmTw	'),
('	FYNBZ	','	"ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman." http://t.co/uRx1ziQU4V	'),
('	BelleCAlvarez	','	Nw: Annabelle.	'),
('	DrawingRoomNYC	','	Edward Snowden Doc Citizenfour Is 2014s Biggest Opening for Non-Fiction http://t.co/qxFiCA3ZXE #nonfictionfilm	'),
('	nfhartman	','	“Jeff_Daniels: Today I dressed up as Harry Dunne and performed Will McAvoys Northwestern speech.  #DumbandDumberTo #Newsroom” jdburke178	'),
('	VisciousTease	','	Guess Ill watch Annabelle by my lonesome.	'),
('	MicahHarshaw	','	"x_Virgo_Vixen_x: Annabelle one bad ass bitch ????? http://t.co/M9GqMT2LNf" _BrettJohnson_ _NinjaNerd MarcusLongoni Kade_Williamson	'),
('	toriallisonb	','	Is it sad that im really excited for #DumbandDumberTo ??????	'),
('	dumbBl0nde_	','	???? “TheBeyHiveTeam: Bey and Jay at the "Nightcrawler" NYC premiere: http://t.co/vTiPQEe4Z3”	'),
('	alisastam	','	"incognito mode STAYS on my phone" -birdman	'),
('	DavidCremaU	','	Annabelle.	'),
('	manalanggirl	','	Annabelle!!!!!!??	'),
('	indigo_k	','	Front row for Birdman. Third to last person in the door.	'),
('	thiagul	','	claaragoomes igual Annabelle	'),
('	ICFTR	','	Bi-Monthly Movie review is up! This time its Annabelle. http://t.co/NvzbuPO9EH head to... http://t.co/DMKiZJnje6	'),
('	lex1223	','	I thought the baby in Annabelle was the cutest little girl. Thats all I kept noticing. Otherwise the movie wasnt that good.	'),
('	UndefinedKelz	','	“ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman.” We aint asked for that album ?????	'),
('	_isabel8	','	“BeyonceLite: Beyoncé Jay Z & Jake Gyllenhaal at the Nightcrawler Premiere in NYC http://t.co/G7FedaOl18” yes jake ??	'),
('	_eitakxx	','	kelsjo55 have you seen Annabelle? ?	'),
('	_Emmitt	','	RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman. http://t.co/ahSus1QyTh	'),
('	JesslovesTune	','	Birdman...................................................................................................................................	'),
('	majason	','	Was just told I look like Keanu Reeves!!! #johnwick #BestDayEver	'),
('	cuntynika	','	RT ComplexMusic: The “Rich Gang 2” album will be released on November 24 according to Birdman. http://t.co/zTs1ztxVo7	'),
('	NoelNomil	','	#Annabelle....too many doll closeups lmfao	'),
('	Cheston_Chin	','	xuenwei ohhh Annabelle part one	'),
('	Smoke_CityBish	','	CobesMom__ I hope that aint wat Birdman got going on man	'),
('	BridgetPeeples	','	Annabelle actually wasnt that scary ? Good but not as scary as I thought .	'),
('	daniellaa_23	','	Why am I watching Annabelle rn ..	'),
('	CountDmitri	','	When did you first fall in love? — "I was twenty years old when I met Annabelle." http://t.co/HOKYIhznRv	'),
('	_FallenBeauty	','	Mystical_Gift hole appeared just to the right of her head} Dont get cocky child. {Victoria kept her calm tone} Annabelle Matthews.<	'),
('	CravenVruel	','	Ready for Nightcrawler this weekend! Ready for bae Mr. Jake Gyllenhaal to spook me out! ??	'),
('	ASmartHollywood	','	Sometimes out of mistakes come the most amazing things #TransformersAgeOfExtinction (2014)	'),
('	transformers	','		'),
('	RichmondJason21	','	still needa watch Whiplash and Birdman some how...	'),
('	SammMinajj	','	ayodeleminaj YASSSSSS wait. Why we hatin on Birdman all the sudden?	'),
('	SlayingOnika	','	Nobody wants that bs Birdman keep it and give us The Pinkprint.	'),
('	reaganwantman	','	A date to see Annabelle or Ouija would be so clutch	'),
('	ETKevinsMind	','	awards_watch Im curious how the Academy will read Whiplash I know Birdman is offbeat but it has two acting wins written all over it!	'),
('	TweetsbyVish	','	mayslesfilms Thanks for a great night! THELadyDane is a FORCE! #TrunkShow #Annabelle #TWOC	')
